package com.NovaCraft.world.village;

import java.util.Random;
import com.NovaCraft.entity.illager.EntityIllagerChief;
import com.NovaCraftBlocks.NovaCraftBlocks;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class VindicatorChiefChurch extends WorldGenerator
{
	private static final Block ironBars = Blocks.iron_bars;
	private static final Block cobbledNullstone = NovaCraftBlocks.cobbled_nullstone;
	private static final Block stairsCobbledNullstone = NovaCraftBlocks.cobbled_nullstone_stairs;
	private static final Block doorWood = Blocks.wooden_door;
	private static final Block ladder = Blocks.ladder;
	private static final Block torchWood = Blocks.redstone_torch;
	private static final Block air = Blocks.air;
	
	protected Block[] GetValidSpawnBlocks() {
		return new Block[] {
			Blocks.snow,
			Blocks.sand,
			Blocks.stone,
			Blocks.grass
		};
	}

	public boolean LocationIsValidSpawn(World world, int i, int j, int k){
		int distanceToAir = 0;
		Block checkID = world.getBlock(i, j, k);

		while (checkID != air){
			distanceToAir++;
			checkID = world.getBlock(i, j + distanceToAir, k);
		}

		if (distanceToAir > 2){
			return false;
		}
		j += distanceToAir - 1;

		Block blockID = world.getBlock(i, j, k);
		Block blockIDAbove = world.getBlock(i, j+1, k);
		Block blockIDBelow = world.getBlock(i, j-1, k);
		for (Block x : GetValidSpawnBlocks()){
			if (blockIDAbove != air){
				return false;
			}
			if ((blockID == Blocks.snow && blockIDBelow == x) || (blockID == Blocks.tallgrass && blockIDBelow == x) || (blockID == Blocks.red_flower && blockIDBelow == x) || (blockID == Blocks.yellow_flower && blockIDBelow == x) || (blockID == Blocks.deadbush && blockIDBelow == x) || (blockID == Blocks.cactus && blockIDBelow == x) || (blockID == Blocks.brown_mushroom && blockIDBelow == x) || (blockID == Blocks.red_mushroom && blockIDBelow == x)){
				return true;
			}
			else if (blockID == x){
				return true;
			}
		}
		return false;
	}

	public VindicatorChiefChurch() { }
	
	public boolean checkAllLocations(World world, int i, int j, int k){
		if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 4, j, k) || !LocationIsValidSpawn(world, i + 4, j, k + 9) || !LocationIsValidSpawn(world, i, j, k + 9) || !AirLocationIsValidSpawn(world, i, j + 12, k) || !AirLocationIsValidSpawn(world, i + 4, j + 12, k) || !AirLocationIsValidSpawn(world, i + 4, j + 12, k + 9) || !AirLocationIsValidSpawn(world, i, j + 12, k + 9))
		{
			return false;
		}
		
		return true;
	}
	
	public boolean AirLocationIsValidSpawn(World world, int i, int j, int k){
		Block blockID = world.getBlock(i, j, k);
		Block blockIDAbove = world.getBlock(i, j+1, k);
		
		if (blockID != air || blockIDAbove != air){
			return false;
		}

		return true;
	}

	public boolean generate(World world, Random rand, int i, int j, int k) {
		//check that each corner is one of the valid spawn blocks
		if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 4, j, k) || !LocationIsValidSpawn(world, i + 4, j, k + 9) || !LocationIsValidSpawn(world, i, j, k + 9) || !AirLocationIsValidSpawn(world, i, j + 12, k) || !AirLocationIsValidSpawn(world, i + 4, j + 12, k) || !AirLocationIsValidSpawn(world, i + 4, j + 12, k + 9) || !AirLocationIsValidSpawn(world, i, j + 12, k + 9))
		{
			return false;
		}

		world.setBlock(i, j + 1, k, air);
		world.setBlock(i, j + 1, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 1, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 1, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 1, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 1, k + 5, air);
		world.setBlock(i, j + 1, k + 6, air);
		world.setBlock(i, j + 1, k + 7, air);
		world.setBlock(i, j + 1, k + 8, air);
		world.setBlock(i, j + 1, k + 9, air);
		world.setBlock(i, j + 2, k, air);
		world.setBlock(i, j + 2, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 2, k + 8, air);
		world.setBlock(i, j + 2, k + 9, air);
		world.setBlock(i, j + 3, k, air);
		world.setBlock(i, j + 3, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 6, ironBars, 0, 2);
		world.setBlock(i, j + 3, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 3, k + 8, air);
		world.setBlock(i, j + 3, k + 9, air);
		world.setBlock(i, j + 4, k, air);
		world.setBlock(i, j + 4, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 4, k + 2, ironBars, 0, 2);
		world.setBlock(i, j + 4, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 4, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 4, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 4, k + 6, ironBars, 0, 2);
		world.setBlock(i, j + 4, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 4, k + 8, air);
		world.setBlock(i, j + 4, k + 9, air);
		world.setBlock(i, j + 5, k, air);
		world.setBlock(i, j + 5, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 5, k + 9, air);
		world.setBlock(i, j + 6, k, air);
		world.setBlock(i, j + 6, k + 1, air);
		world.setBlock(i, j + 6, k + 2, air);
		world.setBlock(i, j + 6, k + 3, air);
		world.setBlock(i, j + 6, k + 4, air);
		world.setBlock(i, j + 6, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 6, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 6, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 6, k + 8, air);
		world.setBlock(i, j + 6, k + 9, air);
		world.setBlock(i, j + 7, k, air);
		world.setBlock(i, j + 7, k + 1, air);
		world.setBlock(i, j + 7, k + 2, air);
		world.setBlock(i, j + 7, k + 3, air);
		world.setBlock(i, j + 7, k + 4, air);
		world.setBlock(i, j + 7, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 7, k + 6, ironBars, 0, 2);
		world.setBlock(i, j + 7, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 7, k + 8, air);
		world.setBlock(i, j + 7, k + 9, air);
		world.setBlock(i, j + 8, k, air);
		world.setBlock(i, j + 8, k + 1, air);
		world.setBlock(i, j + 8, k + 2, air);
		world.setBlock(i, j + 8, k + 3, air);
		world.setBlock(i, j + 8, k + 4, air);
		world.setBlock(i, j + 8, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 8, k + 6, ironBars, 0, 2);
		world.setBlock(i, j + 8, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 8, k + 8, air);
		world.setBlock(i, j + 8, k + 9, air);
		world.setBlock(i, j + 9, k, air);
		world.setBlock(i, j + 9, k + 1, air);
		world.setBlock(i, j + 9, k + 2, air);
		world.setBlock(i, j + 9, k + 3, air);
		world.setBlock(i, j + 9, k + 4, air);
		world.setBlock(i, j + 9, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 9, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 9, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 9, k + 8, air);
		world.setBlock(i, j + 9, k + 9, air);
		world.setBlock(i, j + 10, k, air);
		world.setBlock(i, j + 10, k + 1, air);
		world.setBlock(i, j + 10, k + 2, air);
		world.setBlock(i, j + 10, k + 3, air);
		world.setBlock(i, j + 10, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 10, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 10, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 10, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 10, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 10, k + 9, air);
		world.setBlock(i, j + 11, k, air);
		world.setBlock(i, j + 11, k + 1, air);
		world.setBlock(i, j + 11, k + 2, air);
		world.setBlock(i, j + 11, k + 3, air);
		world.setBlock(i, j + 11, k + 4, air);
		world.setBlock(i, j + 11, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 11, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 11, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 11, k + 8, air);
		world.setBlock(i, j + 11, k + 9, air);
		world.setBlock(i, j + 12, k, air);
		world.setBlock(i, j + 12, k + 1, air);
		world.setBlock(i, j + 12, k + 2, air);
		world.setBlock(i, j + 12, k + 3, air);
		world.setBlock(i, j + 12, k + 4, air);
		world.setBlock(i, j + 12, k + 5, air);
		world.setBlock(i, j + 12, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i, j + 12, k + 7, air);
		world.setBlock(i, j + 12, k + 8, air);
		world.setBlock(i, j + 12, k + 9, air);
		world.setBlock(i + 1, j + 1, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 9, air);
		world.setBlock(i + 1, j + 2, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 2, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 2, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 2, k + 3, stairsCobbledNullstone, 3, 2);
		world.setBlock(i + 1, j + 2, k + 4, air);
		world.setBlock(i + 1, j + 2, k + 5, air);
		world.setBlock(i + 1, j + 2, k + 6, air);
		world.setBlock(i + 1, j + 2, k + 7, air);
		world.setBlock(i + 1, j + 2, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 2, k + 9, air);
		world.setBlock(i + 1, j + 3, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 3, k + 1, stairsCobbledNullstone, 1, 2);
		world.setBlock(i + 1, j + 3, k + 2, air);
		world.setBlock(i + 1, j + 3, k + 3, air);
		world.setBlock(i + 1, j + 3, k + 4, air);
		world.setBlock(i + 1, j + 3, k + 5, air);
		world.setBlock(i + 1, j + 3, k + 6, air);
		world.setBlock(i + 1, j + 3, k + 7, air);
		world.setBlock(i + 1, j + 3, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 3, k + 9, air);
		world.setBlock(i + 1, j + 4, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 4, k + 1, air);
		world.setBlock(i + 1, j + 4, k + 2, air);
		world.setBlock(i + 1, j + 4, k + 3, air);
		world.setBlock(i + 1, j + 4, k + 4, air);
		world.setBlock(i + 1, j + 4, k + 5, air);
		world.setBlock(i + 1, j + 4, k + 6, air);
		world.setBlock(i + 1, j + 4, k + 7, air);
		world.setBlock(i + 1, j + 4, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 4, k + 9, air);
		world.setBlock(i + 1, j + 5, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 1, air);
		world.setBlock(i + 1, j + 5, k + 3, air);
		world.setBlock(i + 1, j + 5, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 5, k + 9, air);
		world.setBlock(i + 1, j + 6, k, air);
		world.setBlock(i + 1, j + 6, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 6, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 6, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 6, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 6, k + 5, air);
		world.setBlock(i + 1, j + 6, k + 6, air);
		world.setBlock(i + 1, j + 6, k + 7, air);
		world.setBlock(i + 1, j + 6, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 6, k + 9, air);
		world.setBlock(i + 1, j + 7, k, air);
		world.setBlock(i + 1, j + 7, k + 1, air);
		world.setBlock(i + 1, j + 7, k + 2, air);
		world.setBlock(i + 1, j + 7, k + 3, air);
		world.setBlock(i + 1, j + 7, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 7, k + 5, air);
		world.setBlock(i + 1, j + 7, k + 6, air);
		world.setBlock(i + 1, j + 7, k + 7, air);
		world.setBlock(i + 1, j + 7, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 7, k + 9, air);
		world.setBlock(i + 1, j + 8, k, air);
		world.setBlock(i + 1, j + 8, k + 1, air);
		world.setBlock(i + 1, j + 8, k + 2, air);
		world.setBlock(i + 1, j + 8, k + 3, air);
		world.setBlock(i + 1, j + 8, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 8, k + 5, air);
		world.setBlock(i + 1, j + 8, k + 6, air);
		world.setBlock(i + 1, j + 8, k + 7, air);
		world.setBlock(i + 1, j + 8, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 8, k + 9, air);
		world.setBlock(i + 1, j + 9, k, air);
		world.setBlock(i + 1, j + 9, k + 1, air);
		world.setBlock(i + 1, j + 9, k + 2, air);
		world.setBlock(i + 1, j + 9, k + 3, air);
		world.setBlock(i + 1, j + 9, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 9, k + 5, air);
		world.setBlock(i + 1, j + 9, k + 6, air);
		world.setBlock(i + 1, j + 9, k + 7, air);
		world.setBlock(i + 1, j + 9, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 9, k + 9, air);
		world.setBlock(i + 1, j + 10, k, air);
		world.setBlock(i + 1, j + 10, k + 1, air);
		world.setBlock(i + 1, j + 10, k + 2, air);
		world.setBlock(i + 1, j + 10, k + 3, air);
		world.setBlock(i + 1, j + 10, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 10, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 10, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 10, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 10, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 10, k + 9, air);
		world.setBlock(i + 1, j + 11, k, air);
		world.setBlock(i + 1, j + 11, k + 1, air);
		world.setBlock(i + 1, j + 11, k + 2, air);
		world.setBlock(i + 1, j + 11, k + 3, air);
		world.setBlock(i + 1, j + 11, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 11, k + 5, air);
		world.setBlock(i + 1, j + 11, k + 6, air);
		world.setBlock(i + 1, j + 11, k + 7, air);
		world.setBlock(i + 1, j + 11, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 1, j + 11, k + 9, air);
		world.setBlock(i + 1, j + 12, k, air);
		world.setBlock(i + 1, j + 12, k + 1, air);
		world.setBlock(i + 1, j + 12, k + 2, air);
		world.setBlock(i + 1, j + 12, k + 3, air);
		world.setBlock(i + 1, j + 12, k + 4, air);
		world.setBlock(i + 1, j + 12, k + 5, air);
		world.setBlock(i + 1, j + 12, k + 6, air);
		world.setBlock(i + 1, j + 12, k + 7, air);
		world.setBlock(i + 1, j + 12, k + 8, air);
		world.setBlock(i + 1, j + 12, k + 9, air);
		world.setBlock(i + 2, j + 1, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 9, stairsCobbledNullstone, 3, 2);
		world.setBlock(i + 2, j + 2, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 2, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 2, k + 2, stairsCobbledNullstone, 3, 2);
		world.setBlock(i + 2, j + 2, k + 3, air);
		world.setBlock(i + 2, j + 2, k + 4, air);
		world.setBlock(i + 2, j + 2, k + 5, air);
		world.setBlock(i + 2, j + 2, k + 6, air);
		world.setBlock(i + 2, j + 2, k + 7, air);
		world.setBlock(i + 2, j + 2, k + 9, air);
		world.setBlock(i + 2, j + 3, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 3, k + 1, air);
		world.setBlock(i + 2, j + 3, k + 2, air);
		world.setBlock(i + 2, j + 3, k + 3, air);
		world.setBlock(i + 2, j + 3, k + 4, air);
		world.setBlock(i + 2, j + 3, k + 5, air);
		world.setBlock(i + 2, j + 3, k + 6, air);
		world.setBlock(i + 2, j + 3, k + 7, air);
		world.setBlock(i + 2, j + 3, k + 9, air);
		world.setBlock(i + 2, j + 4, k, ironBars, 0, 2);
		world.setBlock(i + 2, j + 4, k + 1, air);
		world.setBlock(i + 2, j + 4, k + 2, air);
		world.setBlock(i + 2, j + 4, k + 3, air);
		world.setBlock(i + 2, j + 4, k + 4, air);
		world.setBlock(i + 2, j + 4, k + 5, air);
		world.setBlock(i + 2, j + 4, k + 6, air);
		world.setBlock(i + 2, j + 4, k + 7, air);
		world.setBlock(i + 2, j + 4, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 4, k + 9, air);
		world.setBlock(i + 2, j + 5, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 2, air);
		world.setBlock(i + 2, j + 5, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 5, k + 9, air);
		world.setBlock(i + 2, j + 6, k, air);
		world.setBlock(i + 2, j + 6, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 6, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 6, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 6, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 6, k + 5, air);
		world.setBlock(i + 2, j + 6, k + 6, air);
		world.setBlock(i + 2, j + 6, k + 7, air);
		world.setBlock(i + 2, j + 6, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 6, k + 9, air);
		world.setBlock(i + 2, j + 7, k, air);
		world.setBlock(i + 2, j + 7, k + 1, air);
		world.setBlock(i + 2, j + 7, k + 2, air);
		world.setBlock(i + 2, j + 7, k + 3, air);
		world.setBlock(i + 2, j + 7, k + 4, ironBars, 0, 2);
		world.setBlock(i + 2, j + 7, k + 5, air);
		world.setBlock(i + 2, j + 7, k + 6, air);
		world.setBlock(i + 2, j + 7, k + 7, air);
		world.setBlock(i + 2, j + 7, k + 8, ironBars, 0, 2);
		world.setBlock(i + 2, j + 7, k + 9, air);
		world.setBlock(i + 2, j + 8, k, air);
		world.setBlock(i + 2, j + 8, k + 1, air);
		world.setBlock(i + 2, j + 8, k + 2, air);
		world.setBlock(i + 2, j + 8, k + 3, air);
		world.setBlock(i + 2, j + 8, k + 4, ironBars, 0, 2);
		world.setBlock(i + 2, j + 8, k + 5, air);
		world.setBlock(i + 2, j + 8, k + 6, air);
		world.setBlock(i + 2, j + 8, k + 7, air);
		world.setBlock(i + 2, j + 8, k + 8, ironBars, 0, 2);
		world.setBlock(i + 2, j + 8, k + 9, air);
		world.setBlock(i + 2, j + 9, k, air);
		world.setBlock(i + 2, j + 9, k + 1, air);
		world.setBlock(i + 2, j + 9, k + 2, air);
		world.setBlock(i + 2, j + 9, k + 3, air);
		world.setBlock(i + 2, j + 9, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 9, k + 5, air);
		world.setBlock(i + 2, j + 9, k + 6, air);
		world.setBlock(i + 2, j + 9, k + 7, air);
		world.setBlock(i + 2, j + 9, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 9, k + 9, air);
		world.setBlock(i + 2, j + 10, k, air);
		world.setBlock(i + 2, j + 10, k + 1, air);
		world.setBlock(i + 2, j + 10, k + 2, air);
		world.setBlock(i + 2, j + 10, k + 3, air);
		world.setBlock(i + 2, j + 10, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 10, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 10, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 10, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 10, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 10, k + 9, air);
		world.setBlock(i + 2, j + 11, k, air);
		world.setBlock(i + 2, j + 11, k + 1, air);
		world.setBlock(i + 2, j + 11, k + 2, air);
		world.setBlock(i + 2, j + 11, k + 3, air);
		world.setBlock(i + 2, j + 11, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 11, k + 5, air);
		world.setBlock(i + 2, j + 11, k + 6, air);
		world.setBlock(i + 2, j + 11, k + 7, air);
		world.setBlock(i + 2, j + 11, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 11, k + 9, air);
		world.setBlock(i + 2, j + 12, k, air);
		world.setBlock(i + 2, j + 12, k + 1, air);
		world.setBlock(i + 2, j + 12, k + 2, air);
		world.setBlock(i + 2, j + 12, k + 3, air);
		world.setBlock(i + 2, j + 12, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 12, k + 5, air);
		world.setBlock(i + 2, j + 12, k + 6, air);
		world.setBlock(i + 2, j + 12, k + 7, air);
		world.setBlock(i + 2, j + 12, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 2, j + 12, k + 9, air);
		world.setBlock(i + 3, j + 1, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 9, air);
		world.setBlock(i + 3, j + 2, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 3, stairsCobbledNullstone, 3, 2);
		world.setBlock(i + 3, j + 2, k + 4, air);
		world.setBlock(i + 3, j + 2, k + 6, air);
		world.setBlock(i + 3, j + 2, k + 7, air);
		world.setBlock(i + 3, j + 2, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 9, air);
		world.setBlock(i + 3, j + 3, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 3, k + 1, stairsCobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 3, k + 2, air);
		world.setBlock(i + 3, j + 3, k + 3, air);
		world.setBlock(i + 3, j + 3, k + 4, air);
		world.setBlock(i + 3, j + 3, k + 6, air);
		world.setBlock(i + 3, j + 3, k + 7, air);
		world.setBlock(i + 3, j + 3, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 3, k + 9, air);
		world.setBlock(i + 3, j + 4, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 4, k + 1, air);
		world.setBlock(i + 3, j + 4, k + 2, air);
		world.setBlock(i + 3, j + 4, k + 3, air);
		world.setBlock(i + 3, j + 4, k + 4, air);
		world.setBlock(i + 3, j + 4, k + 6, air);
		world.setBlock(i + 3, j + 4, k + 7, air);
		world.setBlock(i + 3, j + 4, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 4, k + 9, air);
		world.setBlock(i + 3, j + 5, k, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 5, k + 1, air);
		world.setBlock(i + 3, j + 5, k + 3, air);
		world.setBlock(i + 3, j + 5, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 5, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 5, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 5, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 5, k + 9, air);
		world.setBlock(i + 3, j + 6, k, air);
		world.setBlock(i + 3, j + 6, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 6, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 6, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 6, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 6, k + 6, air);
		world.setBlock(i + 3, j + 6, k + 7, air);
		world.setBlock(i + 3, j + 6, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 6, k + 9, air);
		world.setBlock(i + 3, j + 7, k, air);
		world.setBlock(i + 3, j + 7, k + 1, air);
		world.setBlock(i + 3, j + 7, k + 2, air);
		world.setBlock(i + 3, j + 7, k + 3, air);
		world.setBlock(i + 3, j + 7, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 7, k + 6, air);
		world.setBlock(i + 3, j + 7, k + 7, air);
		world.setBlock(i + 3, j + 7, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 7, k + 9, air);
		world.setBlock(i + 3, j + 8, k, air);
		world.setBlock(i + 3, j + 8, k + 1, air);
		world.setBlock(i + 3, j + 8, k + 2, air);
		world.setBlock(i + 3, j + 8, k + 3, air);
		world.setBlock(i + 3, j + 8, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 8, k + 6, air);
		world.setBlock(i + 3, j + 8, k + 7, air);
		world.setBlock(i + 3, j + 8, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 8, k + 9, air);
		world.setBlock(i + 3, j + 9, k, air);
		world.setBlock(i + 3, j + 9, k + 1, air);
		world.setBlock(i + 3, j + 9, k + 2, air);
		world.setBlock(i + 3, j + 9, k + 3, air);
		world.setBlock(i + 3, j + 9, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 9, k + 6, air);
		world.setBlock(i + 3, j + 9, k + 7, air);
		world.setBlock(i + 3, j + 9, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 9, k + 9, air);
		world.setBlock(i + 3, j + 10, k, air);
		world.setBlock(i + 3, j + 10, k + 1, air);
		world.setBlock(i + 3, j + 10, k + 2, air);
		world.setBlock(i + 3, j + 10, k + 3, air);
		world.setBlock(i + 3, j + 10, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 10, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 10, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 10, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 10, k + 9, air);
		world.setBlock(i + 3, j + 11, k, air);
		world.setBlock(i + 3, j + 11, k + 1, air);
		world.setBlock(i + 3, j + 11, k + 2, air);
		world.setBlock(i + 3, j + 11, k + 3, air);
		world.setBlock(i + 3, j + 11, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 11, k + 5, air);
		world.setBlock(i + 3, j + 11, k + 6, air);
		world.setBlock(i + 3, j + 11, k + 7, air);
		world.setBlock(i + 3, j + 11, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 3, j + 11, k + 9, air);
		world.setBlock(i + 3, j + 12, k, air);
		world.setBlock(i + 3, j + 12, k + 1, air);
		world.setBlock(i + 3, j + 12, k + 2, air);
		world.setBlock(i + 3, j + 12, k + 3, air);
		world.setBlock(i + 3, j + 12, k + 4, air);
		world.setBlock(i + 3, j + 12, k + 5, air);
		world.setBlock(i + 3, j + 12, k + 6, air);
		world.setBlock(i + 3, j + 12, k + 7, air);
		world.setBlock(i + 3, j + 12, k + 8, air);
		world.setBlock(i + 3, j + 12, k + 9, air);
		world.setBlock(i + 4, j + 1, k, air);
		world.setBlock(i + 4, j + 1, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 5, air);
		world.setBlock(i + 4, j + 1, k + 6, air);
		world.setBlock(i + 4, j + 1, k + 7, air);
		world.setBlock(i + 4, j + 1, k + 8, air);
		world.setBlock(i + 4, j + 1, k + 9, air);
		world.setBlock(i + 4, j + 2, k, air);
		world.setBlock(i + 4, j + 2, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 8, air);
		world.setBlock(i + 4, j + 2, k + 9, air);
		world.setBlock(i + 4, j + 3, k, air);
		world.setBlock(i + 4, j + 3, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 6, ironBars, 0, 2);
		world.setBlock(i + 4, j + 3, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 3, k + 8, air);
		world.setBlock(i + 4, j + 3, k + 9, air);
		world.setBlock(i + 4, j + 4, k, air);
		world.setBlock(i + 4, j + 4, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 4, k + 2, ironBars, 0, 2);
		world.setBlock(i + 4, j + 4, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 4, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 4, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 4, k + 6, ironBars, 0, 2);
		world.setBlock(i + 4, j + 4, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 4, k + 8, air);
		world.setBlock(i + 4, j + 4, k + 9, air);
		world.setBlock(i + 4, j + 5, k, air);
		world.setBlock(i + 4, j + 5, k + 1, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 2, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 3, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 5, k + 9, air);
		world.setBlock(i + 4, j + 6, k, air);
		world.setBlock(i + 4, j + 6, k + 1, air);
		world.setBlock(i + 4, j + 6, k + 2, air);
		world.setBlock(i + 4, j + 6, k + 3, air);
		world.setBlock(i + 4, j + 6, k + 4, air);
		world.setBlock(i + 4, j + 6, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 6, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 6, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 6, k + 8, air);
		world.setBlock(i + 4, j + 6, k + 9, air);
		world.setBlock(i + 4, j + 7, k, air);
		world.setBlock(i + 4, j + 7, k + 1, air);
		world.setBlock(i + 4, j + 7, k + 2, air);
		world.setBlock(i + 4, j + 7, k + 3, air);
		world.setBlock(i + 4, j + 7, k + 4, air);
		world.setBlock(i + 4, j + 7, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 7, k + 6, ironBars, 0, 2);
		world.setBlock(i + 4, j + 7, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 7, k + 8, air);
		world.setBlock(i + 4, j + 7, k + 9, air);
		world.setBlock(i + 4, j + 8, k, air);
		world.setBlock(i + 4, j + 8, k + 1, air);
		world.setBlock(i + 4, j + 8, k + 2, air);
		world.setBlock(i + 4, j + 8, k + 3, air);
		world.setBlock(i + 4, j + 8, k + 4, air);
		world.setBlock(i + 4, j + 8, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 8, k + 6, ironBars, 0, 2);
		world.setBlock(i + 4, j + 8, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 8, k + 8, air);
		world.setBlock(i + 4, j + 8, k + 9, air);
		world.setBlock(i + 4, j + 9, k, air);
		world.setBlock(i + 4, j + 9, k + 1, air);
		world.setBlock(i + 4, j + 9, k + 2, air);
		world.setBlock(i + 4, j + 9, k + 3, air);
		world.setBlock(i + 4, j + 9, k + 4, air);
		world.setBlock(i + 4, j + 9, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 9, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 9, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 9, k + 8, air);
		world.setBlock(i + 4, j + 9, k + 9, air);
		world.setBlock(i + 4, j + 10, k, air);
		world.setBlock(i + 4, j + 10, k + 1, air);
		world.setBlock(i + 4, j + 10, k + 2, air);
		world.setBlock(i + 4, j + 10, k + 3, air);
		world.setBlock(i + 4, j + 10, k + 4, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 10, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 10, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 10, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 10, k + 8, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 10, k + 9, air);
		world.setBlock(i + 4, j + 11, k, air);
		world.setBlock(i + 4, j + 11, k + 1, air);
		world.setBlock(i + 4, j + 11, k + 2, air);
		world.setBlock(i + 4, j + 11, k + 3, air);
		world.setBlock(i + 4, j + 11, k + 4, air);
		world.setBlock(i + 4, j + 11, k + 5, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 11, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 11, k + 7, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 11, k + 8, air);
		world.setBlock(i + 4, j + 11, k + 9, air);
		world.setBlock(i + 4, j + 12, k, air);
		world.setBlock(i + 4, j + 12, k + 1, air);
		world.setBlock(i + 4, j + 12, k + 2, air);
		world.setBlock(i + 4, j + 12, k + 3, air);
		world.setBlock(i + 4, j + 12, k + 4, air);
		world.setBlock(i + 4, j + 12, k + 5, air);
		world.setBlock(i + 4, j + 12, k + 6, cobbledNullstone, 0, 2);
		world.setBlock(i + 4, j + 12, k + 7, air);
		world.setBlock(i + 4, j + 12, k + 8, air);
		world.setBlock(i + 4, j + 12, k + 9, air);
		world.setBlock(i + 1, j + 5, k + 2, torchWood, 1, 2);
		world.setBlock(i + 2, j + 2, k + 8, doorWood, 3, 2);
		world.setBlock(i + 2, j + 3, k + 8, doorWood, 8, 2);
		world.setBlock(i + 2, j + 5, k + 1, torchWood, 3, 2);
		world.setBlock(i + 2, j + 5, k + 3, torchWood, 4, 2);
		world.setBlock(i + 3, j + 2, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 3, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 4, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 5, k + 2, torchWood, 2, 2);
		world.setBlock(i + 3, j + 5, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 6, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 7, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 8, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 9, k + 5, ladder, 4, 2);
		world.setBlock(i + 3, j + 10, k + 5, ladder, 4, 2);
		
		for(int posX = i; posX <= i + 4; posX++)
			for(int posZ = k; posZ <= k + 9; posZ++){
				int posY = j;				
				boolean isFloorFinished = false;
				while(isFloorFinished == false){				
					if(world.getBlock(posX, posY, posZ) == air || world.getBlock(posX, posY, posZ) == Blocks.tallgrass || world.getBlock(posX, posY, posZ) == Blocks.cactus || world.getBlock(posX, posY, posZ) == Blocks.red_flower || world.getBlock(posX, posY, posZ) == Blocks.yellow_flower || world.getBlock(posX, posY, posZ) == Blocks.deadbush || world.getBlock(posX, posY, posZ) == Blocks.snow || world.getBlock(posX, posY, posZ) == Blocks.water || world.getBlock(posX, posY, posZ) == Blocks.lava || world.getBlock(posX, posY, posZ) == Blocks.brown_mushroom || world.getBlock(posX, posY, posZ) == Blocks.red_mushroom || world.getBlock(posX, posY, posZ) == Blocks.waterlily){
						world.setBlock(posX, posY, posZ, cobbledNullstone, 0, 2);
						posY--;
					}
					else
						isFloorFinished = true;
				}
			}
		
		EntityIllagerChief mob = new EntityIllagerChief(world);
		mob.setPosition(i + 3, j + 2, k + 10);
		world.spawnEntityInWorld(mob);
		
		return true;
	}
}
