package com.NovaCraft.world.ancient_city;

import com.NovaCraft.config.ConfigsCompact;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;
import net.minecraft.tileentity.TileEntityMobSpawner;

public class AncientCitySmallTowerGen2 extends WorldGenerator
{
	public AncientCitySmallTowerGen2() {

	}

	private Block PlaceDeepslateBricks;
	private Block PlaceDeepslateTiles;
	private Block PlaceCrackedDeepslateTiles;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceDeepslateTileStairs;
	private Block PlaceDeepslateBrickWall;

	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Bricks from Et Futurum Requiem, using Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.grimstone_bricks;
			}
		}

		return NovaCraftBlocks.grimstone_bricks;
	}

	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Bricks from Et Futurum Requiem, using Cracked Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_bricks;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_bricks;
	}

	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tiles from Et Futurum Requiem, using Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.grimstone_tiles;
			}
		}

		return NovaCraftBlocks.grimstone_tiles;
	}

	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Tiles from Et Futurum Requiem, using Cracked Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_tiles;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_tiles;
	}

	private Block determineIfDeepslateTileStairsExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_tile_stairs = GameRegistry.findBlock("etfuturum", "deepslate_tile_stairs");
				if (deepslate_tile_stairs != null && (existingBlock == null || existingBlock != deepslate_tile_stairs)) {
					return deepslate_tile_stairs;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tile Stairs from Et Futurum Requiem, using Grimstone Tile Stairs instead...");
				}
				return NovaCraftBlocks.grimstone_tiled_stairs;
			}
		}

		return NovaCraftBlocks.grimstone_tiled_stairs;
	}

	private Block determineIfDeepslateBrickWallExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (ConfigsCompact.enableDeepslateBricks && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_brick_wall = GameRegistry.findBlock("etfuturum", "deepslate_brick_wall");
				if (deepslate_brick_wall != null && (existingBlock == null || existingBlock != deepslate_brick_wall)) {
					return deepslate_brick_wall;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Brick Wall from Et Futurum Requiem, using Grimstone Brick Wall instead...");
				}
				return NovaCraftBlocks.grimstone_brick_wall;
			}
		}

		return NovaCraftBlocks.grimstone_brick_wall;
	}
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 14, j + 9, k + 12);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 8, j + 9, k + 12);
    	PlaceDeepslateTiles = determineIfDeepslateTilesExist(world, i + 8, j + 11, k + 1);
    	PlaceCrackedDeepslateTiles = determineIfCrackedDeepslateTilesExist(world, i + 10, j + 11, k + 1);
    	
    	PlaceDeepslateBrickWall = determineIfDeepslateBrickWallExists(world, i + 11, j + 9, k + 9);
    	PlaceDeepslateTileStairs = determineIfDeepslateTileStairsExists(world, i + 9, j + 12, k + 2);
    	
    	world.setBlock(i + 1, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 9, PlaceDeepslateBrickWall, 1, 2);
		world.setBlock(i + 12, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 12, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 12, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 15, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 5, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 2, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 8, j + 10, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 12, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 15, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 12, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 12, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 12, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 12, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 15, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 9, j + 11, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 10, j + 11, k + 1, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 11, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 1, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 11, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 11, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 1, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 0, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 11, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 9, j + 11, k + 2, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 10, j + 11, k + 2, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 11, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 5, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 12, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 9, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 12, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 9, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 12, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 11, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 11, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 12, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 12, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 11, k + 12, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 12, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 11, k + 12, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 11, k + 12, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 13, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 11, k + 13, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 11, k + 13, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 11, k + 13, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 11, k + 13, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 11, k + 13, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 0, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 10, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 11, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 12, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 13, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 14, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 15, j + 12, k + 2, PlaceDeepslateTileStairs, 2, 2);
		world.setBlock(i + 0, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 10, j + 12, k + 3, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 12, k + 3, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 12, j + 12, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 13, j + 12, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 4, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 10, j + 12, k + 4, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 12, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 4, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 12, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 4, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 10, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 13, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 10, j + 12, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 12, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 12, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 12, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 9, j + 12, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 10, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 7, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 7, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 8, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 12, k + 8, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 8, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 8, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 8, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 10, j + 12, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 12, k + 8, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 12, j + 12, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 13, j + 12, k + 8, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 14, j + 12, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 8, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 10, j + 12, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 12, k + 9, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 9, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 13, j + 12, k + 9, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 9, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 15, j + 12, k + 9, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 0, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 7, j + 12, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 10, j + 12, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 12, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 12, j + 12, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 13, j + 12, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 14, j + 12, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 12, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 11, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 12, k + 11, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 11, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 10, j + 12, k + 11, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 12, k + 11, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 12, j + 12, k + 11, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 13, j + 12, k + 11, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 14, j + 12, k + 11, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 15, j + 12, k + 11, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 0, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 12, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 11, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 12, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 13, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 14, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 15, j + 12, k + 12, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 0, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 2, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 7, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 4, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 3, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 5, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 3, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 5, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 5, j + 13, k + 5, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 6, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 5, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 9, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 6, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 7, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 7, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 5, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 8, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 6, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 9, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 8, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 9, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 10, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 10, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 11, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 11, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 12, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 13, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 13, k + 13, Blocks.air, 0, 2);
		
		world.setBlock(i + 6, j + 13, k + 4, Blocks.mob_spawner, 0, 2);
		TileEntityMobSpawner tileentitymobspawner = (TileEntityMobSpawner)world.getTileEntity(i + 6, j + 13, k + 4);
        
        if (tileentitymobspawner != null)
        {
        	tileentitymobspawner.func_145881_a().setEntityName("nova_craft.sculked_monitor");
        }
        
        world.setBlock(i + 9, j + 13, k + 11, Blocks.mob_spawner, 0, 2);
        TileEntityMobSpawner tileentitymobspawner2 = (TileEntityMobSpawner)world.getTileEntity(i + 9, j + 13, k + 11);
        
        if (tileentitymobspawner2 != null)
        {
        	tileentitymobspawner2.func_145881_a().setEntityName("nova_craft.sculk_incinerator");
        }
    	
    	return true;
    }

}
