package com.NovaCraft.world.ancient_city;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;

public class AncientCityPositiveXLeftBranch3Gen2 extends WorldGenerator
{
	public AncientCityPositiveXLeftBranch3Gen2() {

	}
	
	private Block PlaceDeepslate;
	private Block PlaceDeepslateBricks;
	private Block PlaceDeepslateTiles;
	private Block PlaceCrackedDeepslateTiles;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceChiseledDeepslate;
	private Block PlacePolishedDeepslate;
	private Block PlaceBasalt;

	private Block determineIfDeepslateExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate = GameRegistry.findBlock("etfuturum", "deepslate");
				if (deepslate != null && (existingBlock == null || existingBlock != deepslate)) {
					return deepslate;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate from Et Futurum Requiem, using Grimstone instead...");
				}
				return NovaCraftBlocks.grimstone;
			}
		}

		return NovaCraftBlocks.grimstone;
	}

	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Bricks from Et Futurum Requiem, using Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.grimstone_bricks;
			}
		}

		return NovaCraftBlocks.grimstone_bricks;
	}

	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Bricks from Et Futurum Requiem, using Cracked Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_bricks;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_bricks;
	}

	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tiles from Et Futurum Requiem, using Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.grimstone_tiles;
			}
		}

		return NovaCraftBlocks.grimstone_tiles;
	}

	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Tiles from Et Futurum Requiem, using Cracked Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_tiles;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_tiles;
	}

	private Block determineIfPolishedDeepslateExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block polished_deepslate = GameRegistry.findBlock("etfuturum", "polished_deepslate");
				if (polished_deepslate != null && (existingBlock == null || existingBlock != polished_deepslate)) {
					return polished_deepslate;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Polished Deepslate from Et Futurum Requiem, using Polished Grimstone instead...");
				}
				return NovaCraftBlocks.polished_grimstone;
			}
		}

		return NovaCraftBlocks.polished_grimstone;
	}

	private Block determineIfChiseledDeepslateExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Chiseled Deepslate from Et Futurum Requiem, using Chiseled Grimstone instead...");
				}
				return NovaCraftBlocks.chiseled_grimstone;
			}
		}

		return NovaCraftBlocks.chiseled_grimstone;
	}

	private Block determineIfBasaltExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);

		if (!(Configs.disableNetherliciousBasaltInAncientCity) && Loader.isModLoaded("netherlicious")) {
			try {
				Block nether_Basalt = GameRegistry.findBlock("netherlicious", "Basalt");
				if (nether_Basalt != null && (existingBlock == null || existingBlock != nether_Basalt)) {
					return nether_Basalt;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Failed to Find Netherlicious basalt, trying Et Futurum Requiem...");
				}
			}
		}

		if (Loader.isModLoaded("etfuturum")) {
			try {
				Block et_basalt = GameRegistry.findBlock("etfuturum", "basalt");
				if (et_basalt != null && (existingBlock == null || existingBlock != et_basalt)) {
					return et_basalt;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Failed to Find Et Futurum Requiem basalt, placing Polished Vanite Bricks...");
				}
			}
		}

		return NovaCraftBlocks.polished_vanite_bricks;
	}
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	PlaceDeepslate = determineIfDeepslateExists(world, i + 22, j + 2, k + 28);
    	PlaceBasalt = determineIfBasaltExists(world, i + 10, j + 2, k + 10);
    	
    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 7, j + 2, k + 6);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 13, j + 2, k + 6);    	
    	PlaceDeepslateTiles = determineIfDeepslateTilesExist(world, i + 10, j + 2, k + 2);
    	PlaceCrackedDeepslateTiles = determineIfCrackedDeepslateTilesExist(world, i + 10, j + 2, k + 4);
    	PlaceChiseledDeepslate = determineIfChiseledDeepslateExist(world, i + 10, j + 2, k + 24);
    	PlacePolishedDeepslate = determineIfPolishedDeepslateExists(world, i + 7, j + 2, k + 4);
    	
    	world.setBlock(i + 7, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 4, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 4, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 4, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 6, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 8, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 6, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 14, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 1, j + 2, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 5, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 7, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 7, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 7, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 15, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 1, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 3, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 4, j + 2, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 5, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 7, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 10, PlaceBasalt, 1, 2);
		world.setBlock(i + 11, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 16, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 17, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 18, j + 2, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 19, j + 2, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 20, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 21, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 11, Blocks.ladder, 3, 2);
		world.setBlock(i + 11, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 1, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 5, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 7, j + 2, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 8, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 11, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 14, j + 2, k + 13, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 15, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 13, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 19, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 14, Blocks.planks, 5, 2);
		world.setBlock(i + 8, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 14, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 14, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 14, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 15, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 16, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 16, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 16, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 17, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 18, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 20, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 21, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 22, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 22, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 22, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 23, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 24, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 11, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 24, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 14, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 25, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 11, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 26, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 8, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 26, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 11, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 26, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 14, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 27, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 28, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 28, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 28, PlaceDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 28, PlaceDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 28, PlaceDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 28, PlaceDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 29, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 29, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 29, PlaceDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 29, PlaceDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 29, PlaceDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 29, PlaceDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 30, PlaceDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 30, PlaceDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 30, PlaceDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 30, PlaceDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 31, PlaceDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 31, PlaceDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 31, PlaceDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 31, PlaceDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 33, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 33, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 34, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 34, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 35, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 11, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 0, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 0, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 11, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 0, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 1, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 1, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 14, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 4, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 4, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 11, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 4, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 5, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 14, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 1, j + 3, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 5, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 17, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 7, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 21, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 1, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 4, j + 3, k + 10, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 5, j + 3, k + 10, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 10, PlaceBasalt, 1, 2);
		world.setBlock(i + 11, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 15, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 16, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 17, j + 3, k + 10, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 18, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 19, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 20, j + 3, k + 10, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 21, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 11, Blocks.ladder, 3, 2);
		world.setBlock(i + 11, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 1, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 5, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 8, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 11, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 13, Blocks.planks, 5, 2);
		world.setBlock(i + 14, j + 3, k + 13, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 15, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 17, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 13, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 21, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 14, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 15, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 16, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 16, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 14, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 3, k + 16, Blocks.air, 0, 2);
    	
    	return true;
    }

}
