package com.NovaCraft.world.ancient_city;

import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;

public class AncientCityPositiveHallwayGen4 extends WorldGenerator
{
	public AncientCityPositiveHallwayGen4() {

	}
	
	private static final Block cobbled_deepslate = OtherModBlocks.cobbled_deepslate;
	private static final Block deepslate = OtherModBlocks.deepslate;
	private static final Block sculk_block = NovaCraftBlocks.sculk_block;
	private static final Block soul_lantern = OtherModBlocks.soul_lantern; //1
	private static final Block SoulLantern = OtherModBlocks.SoulLantern;
	private static final Block soul_sand = Blocks.netherrack;
	
	private static final Block polished_deepslate = OtherModBlocks.polished_deepslate;
	private static final Block deepslate_brick_slab = OtherModBlocks.deepslate_brick_slab;
	private static final Block deepslate_tile_stairs = OtherModBlocks.deepslate_tile_stairs;
	private static final Block deepslate_brick_stairs = OtherModBlocks.deepslate_brick_stairs;
	private static final Block polished_deepslate_stairs = OtherModBlocks.polished_deepslate_stairs;
	private static final Block deepslate_wall = OtherModBlocks.deepslate_wall;
	private static final Block fence_dark_oak = OtherModBlocks.fence_dark_oak;	
	private static final Block deepslate_bricks = OtherModBlocks.deepslate_bricks;
	private static final Block cracked_deepslate_bricks = OtherModBlocks.deepslate_bricks;
	private static final Block deepslate_tiles = OtherModBlocks.deepslate_bricks;
	private static final Block cracked_deepslate_tiles = OtherModBlocks.deepslate_bricks;
	private static final Block chiseled_deepslate = OtherModBlocks.deepslate_bricks;
	
	private Block PlaceDeepslate;
	private Block PlaceDeepslateBricks;
	private Block PlaceDeepslateTiles;
	private Block PlaceCrackedDeepslateTiles;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceChiseledDeepslate;
	private Block PlacePolishedDeepslate;
	private Block PlaceSoulLantern;
	private Block PlaceCobbledDeepslate;
	private Block PlaceSoulFire;
	private Block PlaceDarkOakFence;
	
	private Block PlaceDeepslateBrickSlab;
	private Block PlaceDeepslateTileStairs;
	private Block PlaceDeepslateBrickStairs;
	private Block PlacePolishedDeepslateStairs;
	private Block PlaceDeepslateWall;
	
	private Block determineIfDarkOakFenceExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDarkOakFenceInAncientCity == true && (existingBlock == null || existingBlock != fence_dark_oak)) {
            return Blocks.fence;
        } else {
            return fence_dark_oak;
        }
    }
	
	private Block determineIfCobbledDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableCobbledDeepslateInAncientCity == true && (existingBlock == null || existingBlock != cobbled_deepslate)) {
            return NovaCraftBlocks.cobbled_grimstone; // Fallback to grimstone
        } else {
            return cobbled_deepslate; // Default to deepslate
        }
    }
	
	private Block determineIfDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateInAncientCity == true && (existingBlock == null || existingBlock != deepslate)) {
            return NovaCraftBlocks.grimstone; 
        } else {
            return deepslate;
        }
    }
	
	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_bricks)) {
            return NovaCraftBlocks.grimstone_bricks;
        } else {
            return deepslate_bricks;
        }
    }
	
	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != cracked_deepslate_bricks)) {
            return NovaCraftBlocks.cracked_grimstone_bricks;
        } else {
            return cracked_deepslate_bricks;
        }
    }
	
	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_tiles)) {
            return NovaCraftBlocks.grimstone_tiles;
        } else {
            return deepslate_tiles;
        }
    }
	
	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != cracked_deepslate_tiles)) {
            return NovaCraftBlocks.cracked_grimstone_tiles;
        } else {
            return cracked_deepslate_tiles;
        }
    }
	
	private Block determineIfPolishedDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != polished_deepslate)) {
            return NovaCraftBlocks.polished_grimstone;
        } else {
            return polished_deepslate;
        }
    }
	
	private Block determineIfChiseledDeepslateExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != chiseled_deepslate)) {
            return NovaCraftBlocks.chiseled_grimstone;
        } else {
            return chiseled_deepslate;
        }
    }
	
	
	//Slabs, Walls, and Stairs
	private Block determineIfDeepslateTileStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_tile_stairs)) {
            return NovaCraftBlocks.grimstone_tiled_stairs;
        } else {
            return deepslate_tile_stairs;
        }
    }
	
	private Block determineIfDeepslateBrickStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_brick_stairs)) {
            return NovaCraftBlocks.grimstone_brick_stairs;
        } else {
            return deepslate_brick_stairs;
        }
    }
	
	private Block determineIfPolishedDeepslateStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != polished_deepslate_stairs)) {
            return NovaCraftBlocks.grimstone_stairs;
        } else {
            return polished_deepslate_stairs;
        }
    }
	
	private Block determineIfDeepslateWallExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_wall)) {
            return NovaCraftBlocks.cobbled_grimstone_wall;
        } else {
            return deepslate_wall;
        }
    }
	
	private Block determineIfDeepslateSlabExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_brick_slab)) {
            return NovaCraftBlocks.grimstone_brick_slab;
        } else {
            return deepslate_brick_slab;
        }
    }
	
	private Block determineIfSoulLanternExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableEtFuturumSoulLanternInAncientCity == true && Loader.isModLoaded("netherlicious") && (existingBlock == null || existingBlock != soul_lantern)) {
        		return SoulLantern;
        } else if (Loader.isModLoaded("etfuturum") && (existingBlock == null || existingBlock != SoulLantern)) {
            return soul_lantern;
        } else {
        	return Blocks.air;
        }
    }
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	
    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 8, j + 6, k + 12);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 2, j + 6, k + 12);
    	PlaceChiseledDeepslate = determineIfChiseledDeepslateExist(world, i + 5, j + 6, k + 13);
    	PlacePolishedDeepslate = determineIfPolishedDeepslateExists(world, i + 5, j + 6, k + 17);
    	
    	PlaceDeepslateTileStairs = determineIfDeepslateTileStairsExists(world, i + 3, j + 7, k + 0);
    	PlaceSoulLantern = determineIfSoulLanternExists(world, i + 8, j + 1, k + 49);
    	
    	world.setBlock(i + 8, j + 6, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 12, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 12, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 13, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 14, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 14, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 15, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 16, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 16, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 17, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 18, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 18, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 19, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 20, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 21, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 22, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 22, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 23, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 24, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 24, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 25, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 26, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 27, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 29, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 30, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 30, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 31, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 32, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 33, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 34, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 34, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 35, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 36, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 36, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 37, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 38, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 39, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 40, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 41, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 42, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 44, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 47, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 48, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 49, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 50, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 50, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 51, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 52, Blocks.carpet, 9, 2);
		world.setBlock(i + 7, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 54, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 55, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 55, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 56, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 57, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 57, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 58, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 59, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 60, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 61, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 61, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 62, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 63, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 64, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 65, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 66, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 67, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 67, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 68, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 69, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 69, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 70, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 71, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 6, k + 72, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 6, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 0, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 4, j + 7, k + 0, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 5, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 0, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 10, j + 7, k + 0, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 0, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 72, Blocks.air, 0, 2);
		
		world.setBlock(i + 8, j + 1, k + 49, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 8, j + 2, k + 41, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 5, j + 3, k + 28, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 5, j + 3, k + 29, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 2, j + 4, k + 5, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 8, j + 4, k + 11, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 2, j + 4, k + 17, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 8, j + 4, k + 56, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 2, j + 4, k + 62, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 8, j + 4, k + 68, PlaceSoulLantern, 1, 2);
		world.setBlock(i + 5, j + 7, k + 19, PlaceSoulLantern, 0, 2);
		world.setBlock(i + 5, j + 7, k + 25, PlaceSoulLantern, 0, 2);
		world.setBlock(i + 5, j + 7, k + 31, PlaceSoulLantern, 0, 2);
		world.setBlock(i + 5, j + 7, k + 37, PlaceSoulLantern, 0, 2);
    	
    	return true;
    }
    
}