package com.NovaCraft.world.ancient_city;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;

public class AncientCityPositiveXRightBranch2Gen2 extends WorldGenerator
{
	public AncientCityPositiveXRightBranch2Gen2() {

	}

	private Block PlaceDeepslateBricks;
	private Block PlaceDeepslateTiles;
	private Block PlaceCrackedDeepslateTiles;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceChiseledDeepslate;
	private Block PlacePolishedDeepslate;
	private Block PlaceCobbledDeepslate;
	private Block PlaceDeepslateBrickStairs;

	private Block determineIfCobbledDeepslateExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableCobbledDeepslateInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block cobbled_deepslate = GameRegistry.findBlock("etfuturum", "cobbled_deepslate");
				if (cobbled_deepslate != null && (existingBlock == null || existingBlock != cobbled_deepslate)) {
					return cobbled_deepslate;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cobbled Deepslate from Et Futurum Requiem, using Cobbled Grimstone instead...");
				}
				return NovaCraftBlocks.cobbled_grimstone;
			}
		}

		return NovaCraftBlocks.cobbled_grimstone;
	}

	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Bricks from Et Futurum Requiem, using Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.grimstone_bricks;
			}
		}

		return NovaCraftBlocks.grimstone_bricks;
	}

	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Bricks from Et Futurum Requiem, using Cracked Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_bricks;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_bricks;
	}

	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tiles from Et Futurum Requiem, using Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.grimstone_tiles;
			}
		}

		return NovaCraftBlocks.grimstone_tiles;
	}

	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Tiles from Et Futurum Requiem, using Cracked Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_tiles;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_tiles;
	}

	private Block determineIfChiseledDeepslateExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Chiseled Deepslate from Et Futurum Requiem, using Chiseled Grimstone instead...");
				}
				return NovaCraftBlocks.chiseled_grimstone;
			}
		}

		return NovaCraftBlocks.chiseled_grimstone;
	}

	private Block determineIfPolishedDeepslateExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block polished_deepslate = GameRegistry.findBlock("etfuturum", "polished_deepslate");
				if (polished_deepslate != null && (existingBlock == null || existingBlock != polished_deepslate)) {
					return polished_deepslate;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Polished Deepslate from Et Futurum Requiem, using Polished Grimstone instead...");
				}
				return NovaCraftBlocks.polished_grimstone;
			}
		}

		return NovaCraftBlocks.polished_grimstone;
	}

	private Block determineIfDeepslateBrickStairsExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_brick_stairs = GameRegistry.findBlock("etfuturum", "deepslate_brick_stairs");
				if (deepslate_brick_stairs != null && (existingBlock == null || existingBlock != deepslate_brick_stairs)) {
					return deepslate_brick_stairs;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tile Stairs from Et Futurum Requiem, using Grimstone Tile Stairs instead...");
				}
				return NovaCraftBlocks.grimstone_brick_stairs;
			}
		}

		return NovaCraftBlocks.grimstone_brick_stairs;
	}
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	PlaceCobbledDeepslate = determineIfCobbledDeepslateExists(world, i + 15, j + 2, k + 3);

    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 1, j + 1, k + 23);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 7, j + 1, k + 23);
    	PlaceDeepslateTiles = determineIfDeepslateTilesExist(world, i + 4, j + 2, k + 0);
    	PlaceCrackedDeepslateTiles = determineIfCrackedDeepslateTilesExist(world, i + 18, j + 2, k + 6);
    	PlaceChiseledDeepslate = determineIfChiseledDeepslateExist(world, i + 4, j + 2, k + 3);
    	PlacePolishedDeepslate = determineIfPolishedDeepslateExists(world, i + 1, j + 2, k + 1);
    	
    	PlaceDeepslateBrickStairs = determineIfDeepslateBrickStairsExists(world, i + 25, j + 1, k + 32);
    	
    	world.setBlock(i + 13, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 23, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 1, k + 23, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 23, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 1, k + 23, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 5, j + 1, k + 23, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 23, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 23, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 8, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 24, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 1, k + 24, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 24, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 24, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 5, j + 1, k + 24, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 1, k + 24, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 24, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 8, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 1, k + 25, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 25, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 5, j + 1, k + 25, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 25, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 8, j + 1, k + 25, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 10, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 12, j + 1, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 14, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 15, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 16, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 17, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 18, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 19, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 20, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 21, j + 1, k + 25, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 22, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 23, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 24, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 25, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 26, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 27, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 28, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 29, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 30, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 31, j + 1, k + 25, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 1, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 33, j + 1, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 26, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 5, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 8, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 9, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 10, j + 1, k + 26, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 12, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 13, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 14, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 15, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 16, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 17, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 18, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 19, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 20, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 21, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 22, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 23, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 24, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 25, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 26, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 27, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 28, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 29, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 30, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 31, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 32, j + 1, k + 26, Blocks.wool, 7, 2);
		world.setBlock(i + 33, j + 1, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 27, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 5, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 8, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 9, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 10, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 11, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 12, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 13, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 14, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 15, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 16, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 17, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 18, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 19, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 20, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 21, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 22, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 23, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 24, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 25, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 26, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 27, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 28, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 29, j + 1, k + 27, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 30, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 31, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 32, j + 1, k + 27, Blocks.wool, 7, 2);
		world.setBlock(i + 33, j + 1, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 28, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 2, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 5, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 10, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 12, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 13, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 14, j + 1, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 16, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 18, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 19, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 20, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 21, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 22, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 23, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 24, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 25, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 26, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 27, j + 1, k + 28, Blocks.wool, 7, 2);
		world.setBlock(i + 28, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 29, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 30, j + 1, k + 28, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 31, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 1, k + 28, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 33, j + 1, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 29, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 2, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 5, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 8, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 9, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 10, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 11, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 12, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 13, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 14, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 15, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 16, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 17, j + 1, k + 29, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 18, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 19, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 20, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 21, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 22, j + 1, k + 29, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 23, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 24, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 25, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 26, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 27, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 28, j + 1, k + 29, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 29, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 30, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 31, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 32, j + 1, k + 29, Blocks.wool, 7, 2);
		world.setBlock(i + 33, j + 1, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 30, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 2, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 3, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 4, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 5, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 6, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 7, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 8, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 9, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 10, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 11, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 12, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 13, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 14, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 15, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 16, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 17, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 18, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 19, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 20, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 21, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 22, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 23, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 24, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 25, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 26, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 27, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 28, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 29, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 30, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 31, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 32, j + 1, k + 30, Blocks.wool, 7, 2);
		world.setBlock(i + 33, j + 1, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 4, j + 1, k + 31, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 7, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 8, j + 1, k + 31, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 1, k + 31, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 10, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 11, j + 1, k + 31, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 12, j + 1, k + 31, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 13, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 14, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 15, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 16, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 17, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 18, j + 1, k + 31, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 19, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 20, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 21, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 26, j + 1, k + 31, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 27, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 28, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 29, j + 1, k + 31, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 30, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 31, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 1, k + 31, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 33, j + 1, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 32, PlaceDeepslateBrickStairs, 3, 2);
		world.setBlock(i + 26, j + 1, k + 32, PlaceDeepslateBrickStairs, 3, 2);
		world.setBlock(i + 27, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 1, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 0, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 5, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 1, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 2, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 1, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 5, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 1, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 5, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 2, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 31, j + 2, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 3, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 5, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 8, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 18, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 22, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 27, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 29, j + 2, k + 3, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 30, j + 2, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 31, j + 2, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 4, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 5, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 18, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 19, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 20, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 22, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 27, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 28, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 29, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 30, j + 2, k + 4, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 31, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 5, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 5, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 18, j + 2, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 19, j + 2, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 20, j + 2, k + 5, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 21, j + 2, k + 5, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 22, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 28, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 29, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 30, j + 2, k + 5, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 31, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 6, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 6, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 6, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 18, j + 2, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 19, j + 2, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 20, j + 2, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 21, j + 2, k + 6, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 22, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 6, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 29, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 6, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 0, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 7, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 7, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 7, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 29, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 8, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 9, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 9, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 9, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 18, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 9, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 29, j + 2, k + 9, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 30, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 10, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 29, j + 2, k + 10, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 30, j + 2, k + 10, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 31, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 11, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 11, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 11, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 29, j + 2, k + 11, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 30, j + 2, k + 11, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 31, j + 2, k + 11, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 32, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 11, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 0, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 12, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 12, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 12, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 28, j + 2, k + 12, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 29, j + 2, k + 12, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 30, j + 2, k + 12, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 31, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 13, PlaceDeepslateBrickStairs, 6, 2);
		world.setBlock(i + 5, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 13, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 13, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 13, NovaCraftBlocks.sculk_vein, 2, 2);
		world.setBlock(i + 25, j + 2, k + 13, NovaCraftBlocks.sculk_vein, 2, 2);
		world.setBlock(i + 26, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 13, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 28, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 13, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 30, j + 2, k + 13, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 31, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 14, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 5, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 18, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 19, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 20, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 22, j + 2, k + 14, NovaCraftBlocks.sculk_vein, 2, 2);
		world.setBlock(i + 23, j + 2, k + 14, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 24, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 27, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 29, j + 2, k + 14, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 30, j + 2, k + 14, NovaCraftBlocks.sculk_vein, 5, 2);
		world.setBlock(i + 31, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 15, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 15, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 5, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 16, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 17, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 18, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 20, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 21, j + 2, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 22, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 23, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 24, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 25, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 26, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 27, j + 2, k + 15, PlaceCobbledDeepslate, 0, 2);
		world.setBlock(i + 28, j + 2, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 29, j + 2, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 30, j + 2, k + 15, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 31, j + 2, k + 15, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 16, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 5, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 16, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 31, j + 2, k + 16, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 32, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 17, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 2, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 17, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 5, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 17, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 8, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 18, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 2, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 18, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 5, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 18, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 8, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 23, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 24, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 25, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 26, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 27, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 28, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 29, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 30, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 31, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 32, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 33, j + 2, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 19, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 5, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 19, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 20, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 21, j + 2, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 22, j + 2, k + 19, Blocks.air, 0, 2);
    	
    	return true;
    }

}
