package com.NovaCraft.world.ancient_city;

import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnchantmentData;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.Items.NovaCraftItems;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.MathHelper;

public class AncientCityEndPortalGen2 extends WorldGenerator
{
	public AncientCityEndPortalGen2() {

	}
	
	private static final Block cobbled_deepslate = OtherModBlocks.cobbled_deepslate;
	private static final Block deepslate = OtherModBlocks.deepslate;
	private static final Block sculk_block = NovaCraftBlocks.sculk_block;
	private static final Block soul_lantern = OtherModBlocks.soul_lantern; //1
	private static final Block soul_sand = Blocks.netherrack;
	
	private static final Block polished_deepslate = OtherModBlocks.polished_deepslate;
	private static final Block deepslate_brick_slab = OtherModBlocks.deepslate_brick_slab;
	private static final Block deepslate_tile_stairs = OtherModBlocks.deepslate_tile_stairs;
	private static final Block deepslate_brick_stairs = OtherModBlocks.deepslate_brick_stairs;
	private static final Block polished_deepslate_stairs = OtherModBlocks.polished_deepslate_stairs;
	private static final Block deepslate_wall = OtherModBlocks.deepslate_wall;
	private static final Block deepslate_brick_wall = OtherModBlocks.deepslate_brick_wall;
	private static final Block fence_dark_oak = OtherModBlocks.fence_dark_oak;
	private static final Block blue_ice = OtherModBlocks.blue_ice;
	private static final Block iron_trapdoor = OtherModBlocks.iron_trapdoor;
	
	private static final Block deepslate_bricks = OtherModBlocks.deepslate_bricks;
	private static final Block cobbled_deepslate_stairs = OtherModBlocks.cobbled_deepslate_stairs;
	
	private static final Block basalt = OtherModBlocks.Basalt; //netherlicious
	private static final Block basalt1 = OtherModBlocks.basalt; //et futurum requiem
	
	private static final Block smooth_basalt = OtherModBlocks.BasaltBricks; //netherlicious 6
	private static final Block smooth_basalt1 = OtherModBlocks.smooth_basalt; //et futurum requiem

	//0 -> deepslate bricks
	//1 -> cracked deepslate bricks
	//2 -> deepslate tiles
	//3 -> cracked deepslate bricks
	//4 -> chiseled deepslate bricks
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	
    	world.setBlock(i + 8, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 8, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 17, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 4, j + 9, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 5, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 9, NovaCraftBlocks.grimstone_tiled_wall, 0, 2);
		world.setBlock(i + 7, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 9, NovaCraftBlocks.grimstone_tiled_wall, 0, 2);
		world.setBlock(i + 15, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 17, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 10, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 5, j + 9, k + 10, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 6, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 10, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 9, k + 10, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 17, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 11, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 6, j + 9, k + 11, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 7, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 11, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 9, j + 9, k + 11, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 10, j + 9, k + 11, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 11, j + 9, k + 11, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 12, j + 9, k + 11, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 13, j + 9, k + 11, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 14, j + 9, k + 11, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 15, j + 9, k + 11, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 1, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 15, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 2, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 7, j + 10, k + 2, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 8, j + 10, k + 2, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 9, j + 10, k + 2, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 10, j + 10, k + 2, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 11, j + 10, k + 2, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 12, j + 10, k + 2, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 13, j + 10, k + 2, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 14, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 3, NovaCraftBlocks.sculk_growth, 1, 2);
		world.setBlock(i + 4, j + 10, k + 3, NovaCraftBlocks.sculk_growth, 1, 2);
		world.setBlock(i + 5, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 3, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 7, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 3, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 15, j + 10, k + 3, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 4, NovaCraftBlocks.sculk_growth, 1, 2);
		world.setBlock(i + 4, j + 10, k + 4, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 5, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 5, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 4, j + 10, k + 5, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 5, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 5, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 6, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 4, j + 10, k + 6, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 5, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 6, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 4, j + 10, k + 7, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 5, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 7, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 16, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 8, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 5, j + 10, k + 8, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 6, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 8, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 16, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 6, j + 10, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 7, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 15, j + 10, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 16, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 10, k + 10, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 10, j + 10, k + 10, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 11, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 15, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 10, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 3, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 8, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 3, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 10, j + 11, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 11, j + 11, k + 3, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 12, j + 11, k + 3, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 13, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 4, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 8, j + 11, k + 4, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 9, j + 11, k + 4, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 10, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 4, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 13, j + 11, k + 4, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 14, j + 11, k + 4, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 15, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 5, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 6, j + 11, k + 5, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 7, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 5, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 14, j + 11, k + 5, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 15, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 6, NovaCraftBlocks.cracked_sculk_tiles, 0, 2);
		world.setBlock(i + 5, j + 11, k + 6, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 6, j + 11, k + 6, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 7, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 6, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 14, j + 11, k + 6, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 15, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 7, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 4, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 7, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 6, j + 11, k + 7, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 7, j + 11, k + 7, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 8, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 7, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 12, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 7, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 14, j + 11, k + 7, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 15, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 8, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 7, j + 11, k + 8, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 8, j + 11, k + 8, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 9, j + 11, k + 8, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 10, j + 11, k + 8, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 11, j + 11, k + 8, NovaCraftBlocks.vanite_glass, 0, 2);
		world.setBlock(i + 12, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 8, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 14, j + 11, k + 8, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 15, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 9, NovaCraftBlocks.sculk_tiles, 0, 2);
		world.setBlock(i + 9, j + 11, k + 9, NovaCraftBlocks.cracked_grimstone_tiles, 0, 2);
		world.setBlock(i + 10, j + 11, k + 9, NovaCraftBlocks.grimstone_tiles, 0, 2);
		world.setBlock(i + 11, j + 11, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 12, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 9, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 16, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 10, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 9, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 10, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 15, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 11, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 3, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 11, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 9, NovaCraftBlocks.sculk_vein, 1, 2);
		world.setBlock(i + 9, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 9, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 12, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 12, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 12, k + 13, Blocks.air, 0, 2);
		
		world.setBlock(i + 2, j + 1, k + 6, Blocks.chest, 5, 2);
		TileEntityChest chest = (TileEntityChest) world.getTileEntity(i + 2, j + 1, k + 6);

		for (int slot = 0; slot < 3 + random.nextInt(20); slot++) {
			chest.setInventorySlotContents(random.nextInt(chest.getSizeInventory()), this.getEndPortalLoot(random));
		}
		
		world.setBlock(i + 6, j + 7, k + 3, soul_lantern, 1, 2);
		world.setBlock(i + 14, j + 7, k + 9, soul_lantern, 1, 2);
    	
    	return true;
    }
    
    private ItemStack getEndPortalLoot(Random random) {
		int item = random.nextInt(16);
		switch (item) {
			case 0:
				return new ItemStack(Items.ender_pearl, random.nextInt(2) + 1);
			case 1:
				return new ItemStack(NovaCraftBlocks.sculk_block, random.nextInt(8) + 3);
			case 2:
				return new ItemStack(NovaCraftItems.potion_strength_extended);
			case 3:
				return new ItemStack(NovaCraftItems.vanite_ingot, random.nextInt(5) + 3);
			case 4:
				return new ItemStack(Blocks.end_stone, random.nextInt(2) + 1);
			case 5:
				return new ItemStack(NovaCraftItems.pherithium_scraps, random.nextInt(7) + 3);
			case 6:
				return new ItemStack(NovaCraftBlocks.sculk_tentacle_2, random.nextInt(1) + 1);
			case 7: {
				if (random.nextInt(5) == 1) {
					return new ItemStack(NovaCraftItems.echo_shard, 1);
				}

				break;
			}
			case 8: 
				Enchantment enchantment = Enchantment.enchantmentsBookList[random.nextInt(Enchantment.enchantmentsBookList.length)];
		        
				int minLevel = enchantment.getMinLevel();
		        int maxLevel = enchantment.getMaxLevel();
		        int level = MathHelper.getRandomIntegerInRange(random, minLevel, maxLevel);
		        ItemStack itemStack = Items.enchanted_book.getEnchantedItemStack(new EnchantmentData(enchantment, maxLevel));
                
                return itemStack;
			case 9:
				//Pickaxe enchants
			    Enchantment[] pickaxeEnchantments = {Enchantment.efficiency};
			    Enchantment[] pickaxeEnchantments2 = {Enchantment.silkTouch, Enchantment.fortune, Enchantment.unbreaking};
			    Enchantment enchantment3 = pickaxeEnchantments[random.nextInt(pickaxeEnchantments.length)];
			    Enchantment enchantment33 = pickaxeEnchantments2[random.nextInt(pickaxeEnchantments2.length)];	
			    int maxLevel3 = enchantment3.getMaxLevel();			
			    int maxLevel33 = enchantment33.getMaxLevel();	
			    ItemStack itemStack3 = new ItemStack(NovaCraftItems.pherithium_pickaxe);
			    
			    itemStack3.addEnchantment(enchantment3, maxLevel3);
			    itemStack3.addEnchantment(enchantment33, maxLevel33);
			    
			    return itemStack3;
			case 10:
				//Pickaxe enchants
			    Enchantment[] diamondEnchantments = {Enchantment.efficiency};
			    Enchantment[] diamondEnchantments2 = {Enchantment.silkTouch, Enchantment.fortune, Enchantment.unbreaking};
			    Enchantment enchantment4 = diamondEnchantments[random.nextInt(diamondEnchantments.length)];
			    Enchantment enchantment44 = diamondEnchantments2[random.nextInt(diamondEnchantments2.length)];	
			    int maxLevel4 = enchantment4.getMaxLevel();			
			    int maxLevel44 = enchantment44.getMaxLevel();	
			    ItemStack itemStack4 = new ItemStack(Items.diamond_pickaxe);
			    
			    itemStack4.addEnchantment(enchantment4, maxLevel4);
			    itemStack4.addEnchantment(enchantment44, maxLevel44);
			    
			    return itemStack4;
			default: {
				return new ItemStack(NovaCraftBlocks.sculk_block, random.nextInt(9) + 2);
			}
		}
		return new ItemStack(NovaCraftBlocks.sculk_block, random.nextInt(9) + 2);
	}

}
