package com.NovaCraft.world.ancient_city;

import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;

public class AncientCityPositiveHallwayGen2 extends WorldGenerator
{
	public AncientCityPositiveHallwayGen2() {

	}
	
	private static final Block cobbled_deepslate = OtherModBlocks.cobbled_deepslate;
	private static final Block deepslate = OtherModBlocks.deepslate;
	private static final Block sculk_block = NovaCraftBlocks.sculk_block;
	private static final Block soul_lantern = OtherModBlocks.soul_lantern; //1
	private static final Block soul_sand = Blocks.netherrack;
	
	private static final Block polished_deepslate = OtherModBlocks.polished_deepslate;
	private static final Block deepslate_brick_slab = OtherModBlocks.deepslate_brick_slab;
	private static final Block deepslate_tile_stairs = OtherModBlocks.deepslate_tile_stairs;
	private static final Block deepslate_brick_stairs = OtherModBlocks.deepslate_brick_stairs;
	private static final Block polished_deepslate_stairs = OtherModBlocks.polished_deepslate_stairs;
	private static final Block deepslate_wall = OtherModBlocks.deepslate_wall;
	private static final Block fence_dark_oak = OtherModBlocks.fence_dark_oak;	
	private static final Block deepslate_bricks = OtherModBlocks.deepslate_bricks;
	private static final Block cracked_deepslate_bricks = OtherModBlocks.deepslate_bricks;
	private static final Block deepslate_tiles = OtherModBlocks.deepslate_bricks;
	private static final Block cracked_deepslate_tiles = OtherModBlocks.deepslate_bricks;
	private static final Block chiseled_deepslate = OtherModBlocks.deepslate_bricks;
	
	private Block PlaceDeepslate;
	private Block PlaceDeepslateBricks;
	private Block PlaceDeepslateTiles;
	private Block PlaceCrackedDeepslateTiles;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceChiseledDeepslate;
	private Block PlacePolishedDeepslate;
	private Block PlaceSoulLantern;
	private Block PlaceCobbledDeepslate;
	private Block PlaceSoulFire;
	private Block PlaceDarkOakFence;
	
	private Block PlaceDeepslateBrickSlab;
	private Block PlaceDeepslateTileStairs;
	private Block PlaceDeepslateBrickStairs;
	private Block PlacePolishedDeepslateStairs;
	private Block PlaceDeepslateWall;
	
	private Block determineIfDarkOakFenceExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDarkOakFenceInAncientCity == true && (existingBlock == null || existingBlock != fence_dark_oak)) {
            return Blocks.fence;
        } else {
            return fence_dark_oak;
        }
    }
	
	private Block determineIfCobbledDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableCobbledDeepslateInAncientCity == true && (existingBlock == null || existingBlock != cobbled_deepslate)) {
            return NovaCraftBlocks.cobbled_grimstone; // Fallback to grimstone
        } else {
            return cobbled_deepslate; // Default to deepslate
        }
    }
	
	private Block determineIfDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateInAncientCity == true && (existingBlock == null || existingBlock != deepslate)) {
            return NovaCraftBlocks.grimstone; 
        } else {
            return deepslate;
        }
    }
	
	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_bricks)) {
            return NovaCraftBlocks.grimstone_bricks;
        } else {
            return deepslate_bricks;
        }
    }
	
	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != cracked_deepslate_bricks)) {
            return NovaCraftBlocks.cracked_grimstone_bricks;
        } else {
            return cracked_deepslate_bricks;
        }
    }
	
	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_tiles)) {
            return NovaCraftBlocks.grimstone_tiles;
        } else {
            return deepslate_tiles;
        }
    }
	
	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != cracked_deepslate_tiles)) {
            return NovaCraftBlocks.cracked_grimstone_tiles;
        } else {
            return cracked_deepslate_tiles;
        }
    }
	
	private Block determineIfPolishedDeepslateExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != polished_deepslate)) {
            return NovaCraftBlocks.polished_grimstone;
        } else {
            return polished_deepslate;
        }
    }
	
	private Block determineIfChiseledDeepslateExist(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != chiseled_deepslate)) {
            return NovaCraftBlocks.chiseled_grimstone;
        } else {
            return chiseled_deepslate;
        }
    }
	
	
	//Slabs, Walls, and Stairs
	private Block determineIfDeepslateTileStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_tile_stairs)) {
            return NovaCraftBlocks.grimstone_tiled_stairs;
        } else {
            return deepslate_tile_stairs;
        }
    }
	
	private Block determineIfDeepslateBrickStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_brick_stairs)) {
            return NovaCraftBlocks.grimstone_brick_stairs;
        } else {
            return deepslate_brick_stairs;
        }
    }
	
	private Block determineIfPolishedDeepslateStairsExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != polished_deepslate_stairs)) {
            return NovaCraftBlocks.grimstone_stairs;
        } else {
            return polished_deepslate_stairs;
        }
    }
	
	private Block determineIfDeepslateWallExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_wall)) {
            return NovaCraftBlocks.cobbled_grimstone_wall;
        } else {
            return deepslate_wall;
        }
    }
	
	private Block determineIfDeepslateSlabExists(World world, int x, int y, int z) {
        Block existingBlock = world.getBlock(x, y, z);

        if (Configs.disableDeepslateBricksInAncientCity == true && (existingBlock == null || existingBlock != deepslate_brick_slab)) {
            return NovaCraftBlocks.grimstone_brick_slab;
        } else {
            return deepslate_brick_slab;
        }
    }
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 2, j + 2, k + 52);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 8, j + 2, k + 52);
    	PlaceDeepslateTiles = determineIfDeepslateTilesExist(world, i + 5, j + 2, k + 50);
    	PlaceCrackedDeepslateTiles = determineIfCrackedDeepslateTilesExist(world, i + 5, j + 2, k + 51);
    	PlaceChiseledDeepslate = determineIfChiseledDeepslateExist(world, i + 5, j + 2, k + 52);
    	
    	PlacePolishedDeepslate = determineIfPolishedDeepslateExists(world, i + 8, j + 2, k + 44);
    	PlaceDeepslateBrickStairs = determineIfDeepslateBrickStairsExists(world, i + 5, j + 3, k + 26);
    	PlaceDeepslateTileStairs = determineIfDeepslateTileStairsExists(world, i + 3, j + 4, k + 0);
    	
    	world.setBlock(i + 8, j + 2, k + 44, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 50, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 50, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 51, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 51, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 52, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 52, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 52, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 53, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 53, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 54, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 54, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 54, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 55, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 3, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 55, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 55, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 56, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 56, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 57, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 57, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 57, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 58, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 59, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 59, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 59, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 60, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 60, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 64, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 64, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 65, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 65, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 65, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 66, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 67, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 67, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 67, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 68, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 68, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 69, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 69, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 69, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 70, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 71, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 71, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 71, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 72, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 72, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 1, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 2, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 2, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 2, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 4, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 4, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 5, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 6, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 6, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 7, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 8, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 8, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 8, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 9, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 10, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 10, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 11, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 12, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 13, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 14, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 14, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 14, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 15, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 16, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 16, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 17, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 19, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 20, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 21, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 21, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 22, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 22, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 23, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 24, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 25, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 26, PlaceDeepslateBrickStairs, 7, 2);
		world.setBlock(i + 6, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 30, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 31, PlaceDeepslateBrickStairs, 6, 2);
		world.setBlock(i + 6, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 31, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 32, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 6, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 32, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 33, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 33, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 34, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 34, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 35, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 35, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 36, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 36, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 37, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 37, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 38, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 38, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 38, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 39, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 39, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 40, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 40, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 41, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 42, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 43, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 44, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 44, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 45, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 46, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 47, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 48, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 49, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 50, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 50, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 51, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 52, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 52, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 52, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 53, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 53, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 54, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 54, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 55, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 55, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 56, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 56, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 57, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 57, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 58, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 58, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 59, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 59, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 59, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 60, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 61, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 62, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 63, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 64, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 64, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 65, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 65, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 65, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 65, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 66, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 67, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 67, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 68, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 6, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 68, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 69, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 69, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 70, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 70, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 71, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 71, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 71, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 71, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 72, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 72, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 0, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 1, j + 4, k + 0, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 2, j + 4, k + 0, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 3, j + 4, k + 0, PlaceDeepslateTileStairs, 7, 2);
		world.setBlock(i + 4, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 0, PlaceDeepslateTileStairs, 3, 2);
		world.setBlock(i + 8, j + 4, k + 0, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 9, j + 4, k + 0, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 10, j + 4, k + 0, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 0, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 1, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 2, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 2, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 2, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 3, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 4, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 5, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 6, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 7, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 3, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 8, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 8, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 10, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 11, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 12, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 12, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 14, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 14, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 14, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 15, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 16, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 16, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 16, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 17, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 17, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 17, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 18, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 18, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 19, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 19, NovaCraftBlocks.sculk_block, 0, 2);
		world.setBlock(i + 9, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 19, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 3, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 20, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 20, PlacePolishedDeepslate, 0, 2);
		world.setBlock(i + 9, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 20, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 21, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 21, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 22, PlaceCrackedDeepslateTiles, 3, 2);
		world.setBlock(i + 6, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 22, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 23, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 23, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 24, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 24, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 25, PlaceDeepslateTiles, 2, 2);
		world.setBlock(i + 6, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 25, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 26, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 26, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 27, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 6, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 27, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 28, PlaceChiseledDeepslate, 4, 2);
		world.setBlock(i + 6, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 28, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 29, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 29, Blocks.air, 0, 2);
    	
    	return true;
    }
    
}