package com.NovaCraft.world.ancient_city;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import cpw.mods.fml.common.Loader;
import net.minecraft.init.*;

public class AncientCityIceRoomAlternateGen2 extends WorldGenerator
{
	public AncientCityIceRoomAlternateGen2() {

	}
	private Block PlaceDeepslateBricks;
	private Block PlaceCrackedDeepslateBricks;
	private Block PlaceDeepslateBrickStairs;
	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Bricks from Et Futurum Requiem, using Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.grimstone_bricks;
			}
		}

		return NovaCraftBlocks.grimstone_bricks;
	}

	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Bricks from Et Futurum Requiem, using Cracked Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_bricks;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_bricks;
	}

	private Block determineIfDeepslateBrickStairsExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_brick_stairs = GameRegistry.findBlock("etfuturum", "deepslate_brick_stairs");
				if (deepslate_brick_stairs != null && (existingBlock == null || existingBlock != deepslate_brick_stairs)) {
					return deepslate_brick_stairs;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tile Stairs from Et Futurum Requiem, using Grimstone Tile Stairs instead...");
				}
				return NovaCraftBlocks.grimstone_brick_stairs;
			}
		}

		return NovaCraftBlocks.grimstone_brick_stairs;
	}
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 8, j + 8, k + 3);
    	PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 16, j + 8, k + 4);
    	PlaceDeepslateBrickStairs = determineIfDeepslateBrickStairsExists(world, i + 5, j + 8, k + 7);
    	
    	world.setBlock(i + 3, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 7, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 7, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 3, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 9, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 4, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 5, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 7, PlaceDeepslateBrickStairs, 2, 2);
		world.setBlock(i + 6, j + 8, k + 7, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 7, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 8, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 8, k + 8, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 7, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 12, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 6, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 13, PlaceDeepslateBricks, 0, 2);
		world.setBlock(i + 16, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 8, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 4, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 5, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 16, j + 9, k + 5, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 6, PlaceCrackedDeepslateBricks, 1, 2);
		world.setBlock(i + 17, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 13, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 14, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 14, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 15, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 16, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 17, j + 9, k + 15, Blocks.air, 0, 2);
		world.setBlock(i + 18, j + 9, k + 15, Blocks.air, 0, 2);
    	
    	return true;
    }

}
