package com.NovaCraft.world.ancient_city;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;

import com.NovaCraft.config.Configs;
import com.NovaCraft.registry.OtherModBlocks;
import com.NovaCraftBlocks.NovaCraftBlocks;

import net.minecraft.init.*;

public class AncientCityNegativeHallwayGen2 extends WorldGenerator
{
	public AncientCityNegativeHallwayGen2() {

	}
		private Block PlaceDeepslateBricks;
		private Block PlaceDeepslateTiles;
		private Block PlaceCrackedDeepslateTiles;
		private Block PlaceCrackedDeepslateBricks;
		private Block PlaceChiseledDeepslate;
		private Block PlacePolishedDeepslate;
		
		private Block PlaceDeepslateBrickSlab;
		private Block PlaceDeepslateTileStairs;

	private Block determineIfDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Bricks from Et Futurum Requiem, using Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.grimstone_bricks;
			}
		}

		return NovaCraftBlocks.grimstone_bricks;
	}

	private Block determineIfCrackedDeepslateBricksExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Bricks from Et Futurum Requiem, using Cracked Grimstone Bricks instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_bricks;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_bricks;
	}

	private Block determineIfDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tiles from Et Futurum Requiem, using Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.grimstone_tiles;
			}
		}

		return NovaCraftBlocks.grimstone_tiles;
	}

	private Block determineIfCrackedDeepslateTilesExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Cracked Deepslate Tiles from Et Futurum Requiem, using Cracked Grimstone Tiles instead...");
				}
				return NovaCraftBlocks.cracked_grimstone_tiles;
			}
		}

		return NovaCraftBlocks.cracked_grimstone_tiles;
	}

	private Block determineIfChiseledDeepslateExist(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_bricks = GameRegistry.findBlock("etfuturum", "deepslate_bricks");
				if (deepslate_bricks != null && (existingBlock == null || existingBlock != deepslate_bricks)) {
					return deepslate_bricks;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Chiseled Deepslate from Et Futurum Requiem, using Chiseled Grimstone instead...");
				}
				return NovaCraftBlocks.chiseled_grimstone;
			}
		}

		return NovaCraftBlocks.chiseled_grimstone;
	}

	private Block determineIfPolishedDeepslateExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block polished_deepslate = GameRegistry.findBlock("etfuturum", "polished_deepslate");
				if (polished_deepslate != null && (existingBlock == null || existingBlock != polished_deepslate)) {
					return polished_deepslate;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Polished Deepslate from Et Futurum Requiem, using Polished Grimstone instead...");
				}
				return NovaCraftBlocks.polished_grimstone;
			}
		}

		return NovaCraftBlocks.polished_grimstone;
	}
		
		
	//Slabs, Walls, and Stairs
	private Block determineIfDeepslateTileStairsExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_tile_stairs = GameRegistry.findBlock("etfuturum", "deepslate_tile_stairs");
				if (deepslate_tile_stairs != null && (existingBlock == null || existingBlock != deepslate_tile_stairs)) {
					return deepslate_tile_stairs;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Tile Stairs from Et Futurum Requiem, using Grimstone Tile Stairs instead...");
				}
				return NovaCraftBlocks.grimstone_tiled_stairs;
			}
		}

		return NovaCraftBlocks.grimstone_tiled_stairs;
	}

	private Block determineIfDeepslateSlabExists(World world, int x, int y, int z) {
		Block existingBlock = world.getBlock(x, y, z);
		if (Configs.enableDeepslateBricksInAncientCity && Loader.isModLoaded("etfuturum")) {
			try {
				Block deepslate_brick_slab = GameRegistry.findBlock("etfuturum", "deepslate_brick_slab");
				if (deepslate_brick_slab != null && (existingBlock == null || existingBlock != deepslate_brick_slab)) {
					return deepslate_brick_slab;
				}
			} catch (Exception ex) {
				if (Configs.enableDebugMode) {
					System.out.println("Missing Deepslate Brick Slab from Et Futurum Requiem, using Grimstone Brick Slab instead...");
				}
				return NovaCraftBlocks.grimstone_brick_slab;
			}
		}

		return NovaCraftBlocks.grimstone_brick_slab;
	}
	
	 public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
		 PlaceDeepslateBricks = determineIfDeepslateBricksExists(world, i + 10, j + 2, k + 51);
		 PlaceCrackedDeepslateBricks = determineIfCrackedDeepslateBricksExists(world, i + 4, j + 2, k + 51);
		 PlaceDeepslateTiles = determineIfDeepslateTilesExist(world, i + 7, j + 2, k + 43);
		 PlaceCrackedDeepslateTiles = determineIfCrackedDeepslateTilesExist(world, i + 7, j + 2, k + 52);
		 PlaceChiseledDeepslate = determineIfChiseledDeepslateExist(world, i + 7, j + 2, k + 51);
		 PlacePolishedDeepslate = determineIfPolishedDeepslateExists(world, i + 4, j + 2, k + 43);
		 
		 PlaceDeepslateTileStairs = determineIfDeepslateTileStairsExists(world, i + 7, j + 2, k + 44);
		 PlaceDeepslateBrickSlab = determineIfDeepslateSlabExists(world, i + 7, j + 3, k + 7);
		 
		    world.setBlock(i + 0, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 43, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 43, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 43, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 44, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 44, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 8, j + 2, k + 44, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 9, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 48, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 48, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 7, j + 2, k + 48, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 8, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 48, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 49, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 49, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 49, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 50, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 50, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 50, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 51, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 5, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 51, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 51, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 11, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 52, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 52, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 52, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 53, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 5, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 53, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 53, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 11, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 54, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 55, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 55, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 55, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 56, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 56, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 56, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 57, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 5, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 57, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 57, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 11, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 58, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 58, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 59, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 5, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 59, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 59, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 11, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 60, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 60, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 60, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 61, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 61, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 61, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 62, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 62, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 66, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 66, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 67, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 67, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 67, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 68, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 68, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 68, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 69, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 5, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 69, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 69, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 11, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 70, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 71, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 5, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 71, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 71, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 11, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 2, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 0, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 0, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 1, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 1, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 1, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 2, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 3, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 3, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 4, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 6, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 7, PlaceDeepslateBrickSlab, 7, 2);
			world.setBlock(i + 8, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 11, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 12, PlaceDeepslateBrickSlab, 6, 2);
			world.setBlock(i + 8, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 12, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 13, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 13, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 14, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 8, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 14, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 15, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 15, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 15, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 16, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 16, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 17, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 17, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 18, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 18, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 19, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 19, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 20, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 20, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 21, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 21, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 21, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 9, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 21, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 22, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 22, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 8, j + 3, k + 22, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 9, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 22, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 22, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 23, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 24, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 25, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 26, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 27, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 28, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 28, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 7, j + 3, k + 28, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 8, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 28, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 28, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 29, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 29, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 30, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 30, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 30, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 31, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 31, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 32, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 33, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 8, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 33, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 33, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 34, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 34, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 34, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 34, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 35, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 35, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 36, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 8, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 36, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 37, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 37, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 37, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 38, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 38, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 39, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 39, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 40, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 40, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 40, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 41, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 41, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 41, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 41, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 42, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 42, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 42, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 42, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 43, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 43, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 8, j + 3, k + 43, PlaceDeepslateTileStairs, 3, 2);
			world.setBlock(i + 9, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 43, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 43, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 44, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 45, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 46, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 47, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 48, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 48, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 49, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 49, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 7, j + 3, k + 49, PlaceDeepslateTileStairs, 2, 2);
			world.setBlock(i + 8, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 49, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 49, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 50, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 50, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 50, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 50, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 51, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 51, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 52, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 52, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 53, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 53, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 54, PlaceCrackedDeepslateBricks, 1, 2);
			world.setBlock(i + 8, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 54, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 55, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 55, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 55, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 56, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 56, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 56, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 57, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 57, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 58, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 58, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 59, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 59, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 60, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 60, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 60, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 61, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 61, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 61, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 61, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 62, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 62, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 63, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 64, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 65, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 66, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 67, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 67, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 67, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 67, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 68, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 68, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 68, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 69, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 69, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 69, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 70, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 8, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 70, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 70, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 71, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 71, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 11, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 71, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 8, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 3, k + 72, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 0, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 0, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 1, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 5, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 1, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 1, PlacePolishedDeepslate, 0, 2);
			world.setBlock(i + 11, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 1, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 2, NovaCraftBlocks.sculk_block, 0, 2);
			world.setBlock(i + 5, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 2, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 2, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 3, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 3, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 4, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 4, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 5, PlaceCrackedDeepslateTiles, 3, 2);
			world.setBlock(i + 8, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 5, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 6, PlaceDeepslateTiles, 2, 2);
			world.setBlock(i + 8, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 6, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 7, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 7, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 8, PlaceDeepslateBricks, 0, 2);
			world.setBlock(i + 8, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 8, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 2, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 3, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 4, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 5, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 6, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 7, j + 4, k + 9, PlaceChiseledDeepslate, 4, 2);
			world.setBlock(i + 8, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 9, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 10, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 11, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 12, j + 4, k + 9, Blocks.air, 0, 2);
			world.setBlock(i + 0, j + 4, k + 10, Blocks.air, 0, 2);
			world.setBlock(i + 1, j + 4, k + 10, Blocks.air, 0, 2);	
			
		 return true;
	 }

}
