package com.NovaCraft.world.floating_island;
import com.NovaCraft.Items.NovaCraftItems;
import com.NovaCraftBlocks.NovaCraftBlocks;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenAbstractTree;
import net.minecraft.world.gen.feature.WorldGenerator;

import java.util.Random;

public class FloatingIslandAltar extends WorldGenerator
{
    public FloatingIslandAltar() {

    }

    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
        world.setBlock(i + 12, j + 0, k + 0, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 0, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 1, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 1, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 2, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 2, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 2, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 2, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 9, j + 0, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 9, j + 0, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 0, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 15, j + 0, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 0, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j + 0, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 0, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 17, j + 0, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 0, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 17, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 21, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 22, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 23, j + 0, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j + 0, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 0, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 20, j + 0, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 21, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 0, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 24, j + 0, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 0, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 19, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 20, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 24, j + 0, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 25, j + 0, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 0, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 19, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 20, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 24, j + 0, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 25, j + 0, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 0, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 19, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 20, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 24, j + 0, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 25, j + 0, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j + 0, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 0, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 20, j + 0, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 21, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 0, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 24, j + 0, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 17, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 21, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 22, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 23, j + 0, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j + 0, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 0, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 17, j + 0, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 0, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 8, j + 0, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 9, j + 0, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 0, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 15, j + 0, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 0, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 9, j + 0, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 16, j + 0, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 10, j + 0, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 22, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 0, k + 22, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 22, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 22, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 0, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 11, j + 0, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 23, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 0, k + 23, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 0, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 0, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 13, j + 0, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 12, j + 1, k + 2, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 1, k + 2, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 12, j + 1, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 1, k + 3, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 1, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 1, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 1, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 1, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 1, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 1, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 2, j + 1, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 1, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 1, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 1, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 2, j + 1, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 1, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 13, j + 1, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 21, j + 1, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 1, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 1, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 2, j + 1, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 1, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 1, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 23, j + 1, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 8, j + 1, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 1, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 1, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 1, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 1, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 1, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 1, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 1, k + 21, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 1, k + 22, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 1, k + 22, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 12, j + 2, k + 3, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 2, k + 3, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 12, j + 2, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 2, k + 4, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 2, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 2, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 2, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 2, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 2, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 2, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 3, j + 2, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 4, j + 2, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 2, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 2, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 2, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 2, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 3, j + 2, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 4, j + 2, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 2, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 2, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 13, j + 2, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 20, j + 2, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 2, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 2, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 3, j + 2, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 4, j + 2, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 2, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 2, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 2, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 22, j + 2, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 8, j + 2, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 2, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 2, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 2, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 2, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 2, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 2, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 2, k + 20, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 2, k + 21, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 2, k + 21, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 12, j + 3, k + 4, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 3, k + 4, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 12, j + 3, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 3, k + 5, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 3, k + 6, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 3, k + 6, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 3, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 3, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 3, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 3, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 4, j + 3, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 5, j + 3, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 3, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 3, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 3, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 3, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 4, j + 3, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 5, j + 3, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 3, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 3, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 13, j + 3, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 19, j + 3, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 3, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 3, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 4, j + 3, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 5, j + 3, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 3, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 3, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 3, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 21, j + 3, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 8, j + 3, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 3, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 3, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 3, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 3, k + 18, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 3, k + 18, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 3, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 3, k + 19, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 3, k + 20, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 3, k + 20, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 12, j + 4, k + 5, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 4, k + 5, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 12, j + 4, k + 6, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 4, k + 6, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 4, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 4, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 4, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 4, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 4, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 4, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 5, j + 4, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 4, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 4, k + 11, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 13, j + 4, k + 11, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 4, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 4, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 4, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 5, j + 4, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 4, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 4, k + 12, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 4, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 4, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 5, j + 4, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 4, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 4, k + 13, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 13, j + 4, k + 13, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 4, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 4, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 20, j + 4, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 8, j + 4, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 4, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 4, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 4, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 4, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 4, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 4, k + 18, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 4, k + 18, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 4, k + 19, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 4, k + 19, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 12, j + 5, k + 6, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 5, k + 6, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 9, j + 5, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 11, j + 5, k + 7, placeEtherstoneBrickStairs(random), 4, 2);
        world.setBlock(i + 12, j + 5, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 5, k + 7, placeEtherstoneBrickStairs(random), 5, 2);
        world.setBlock(i + 16, j + 5, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 5, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 5, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 5, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 5, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 5, k + 10, placeEtherstoneBrickStairs(random), 6, 2);
        world.setBlock(i + 12, j + 5, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 5, k + 10, placeEtherstoneBrickStairs(random), 6, 2);
        world.setBlock(i + 6, j + 5, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 7, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 5, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 5, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 6, j + 5, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 7, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 5, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 5, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 6, j + 5, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 7, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 5, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 19, j + 5, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 7, j + 5, k + 14, placeEtherstoneBrickStairs(random), 7, 2);
        world.setBlock(i + 12, j + 5, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 5, k + 14, placeEtherstoneBrickStairs(random), 7, 2);
        world.setBlock(i + 12, j + 5, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 5, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 5, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 5, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 5, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 11, j + 5, k + 17, placeEtherstoneBrickStairs(random), 4, 2);
        world.setBlock(i + 12, j + 5, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 5, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 5, k + 17, placeEtherstoneBrickStairs(random), 5, 2);
        world.setBlock(i + 16, j + 5, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 5, k + 18, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 5, k + 18, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 9, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 7, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 13, j + 6, k + 7, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 14, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 8, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 8, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 9, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 9, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 9, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 9, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 9, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 10, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 10, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 6, k + 11, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 11, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 11, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 11, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 11, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 11, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 7, j + 6, k + 12, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 12, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 12, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 12, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 12, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 12, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 12, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 12, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 7, j + 6, k + 13, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 13, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 13, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 13, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 13, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 13, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 7, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 14, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 14, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 15, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 15, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 15, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 15, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 15, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 6, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 16, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 13, j + 6, k + 16, placeCarvedVaniteBricks(random), 0, 2);
        world.setBlock(i + 14, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 6, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 12, j + 6, k + 17, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 13, j + 6, k + 17, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 14, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 6, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 7, k + 7, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 7, k + 8, placeEtherstoneBrickStairs(random), 0, 2);
        world.setBlock(i + 16, j + 7, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 7, k + 8, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 7, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 9, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 17, j + 7, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 7, k + 9, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 7, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 10, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 11, j + 7, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 12, j + 7, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 13, j + 7, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 14, j + 7, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 15, j + 7, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 17, j + 7, k + 10, placeEtherstoneBrickStairs(random), 3, 2);
        world.setBlock(i + 18, j + 7, k + 10, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 7, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 12, j + 7, k + 11, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 13, j + 7, k + 11, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 7, k + 11, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 15, j + 7, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 11, j + 7, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 12, j + 7, k + 12, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 13, j + 7, k + 12, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 7, k + 12, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 15, j + 7, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 11, j + 7, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 12, j + 7, k + 13, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 13, j + 7, k + 13, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 7, k + 13, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 15, j + 7, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 7, j + 7, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 14, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 11, j + 7, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 12, j + 7, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 13, j + 7, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 14, j + 7, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 15, j + 7, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 17, j + 7, k + 14, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 18, j + 7, k + 14, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 7, j + 7, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 15, placeEtherstoneBrickStairs(random), 2, 2);
        world.setBlock(i + 17, j + 7, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 18, j + 7, k + 15, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 8, j + 7, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 7, k + 16, placeEtherstoneBrickStairs(random), 1, 2);
        world.setBlock(i + 16, j + 7, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 17, j + 7, k + 16, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 10, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 11, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 14, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 15, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 16, j + 7, k + 17, placeEtherstoneBricks(random), 0, 2);
        world.setBlock(i + 9, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 10, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 11, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 14, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 15, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 8, k + 7, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 8, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 8, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 8, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 8, k + 8, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 7, j + 8, k + 9, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 8, k + 9, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 8, k + 9, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 8, k + 9, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 7, j + 8, k + 10, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 8, k + 10, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 12, j + 8, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 8, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 12, j + 8, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 8, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 7, j + 8, k + 14, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 8, k + 14, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 7, j + 8, k + 15, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 8, k + 15, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 8, k + 15, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 18, j + 8, k + 15, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 8, j + 8, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 8, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 8, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 17, j + 8, k + 16, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 9, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 10, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 11, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 14, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 15, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 16, j + 8, k + 17, NovaCraftBlocks.etherstone_tiled_wall, 0, 2);
        world.setBlock(i + 11, j + 9, k + 7, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 14, j + 9, k + 7, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 9, j + 9, k + 8, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 16, j + 9, k + 8, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 7, j + 9, k + 10, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 18, j + 9, k + 10, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 12, j + 9, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 9, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 12, j + 9, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 9, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 7, j + 9, k + 14, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 18, j + 9, k + 14, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 9, j + 9, k + 16, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 16, j + 9, k + 16, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 11, j + 9, k + 17, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 14, j + 9, k + 17, NovaCraftBlocks.vanite_torch, 5, 2);
        world.setBlock(i + 12, j + 10, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 10, k + 11, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 12, j + 10, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 14, j + 10, k + 13, NovaCraftBlocks.vanite_brick_wall, 0, 2);
        world.setBlock(i + 12, j + 11, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 13, j + 11, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 14, j + 11, k + 10, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 11, j + 11, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 12, j + 11, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 13, j + 11, k + 11, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 11, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 15, j + 11, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 11, j + 11, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 12, j + 11, k + 12, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 13, j + 11, k + 12, NovaCraftBlocks.glowing_carved_vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 11, k + 12, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 15, j + 11, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 11, j + 11, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 12, j + 11, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 13, j + 11, k + 13, NovaCraftBlocks.vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 11, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 15, j + 11, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 12, j + 11, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 13, j + 11, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 14, j + 11, k + 14, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);
        world.setBlock(i + 13, j + 12, k + 11, NovaCraftBlocks.carved_vanite_brick_stairs, 2, 2);
        world.setBlock(i + 12, j + 12, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 0, 2);
        world.setBlock(i + 13, j + 12, k + 12, NovaCraftBlocks.glowing_carved_vanite_bricks, 0, 2);
        world.setBlock(i + 14, j + 12, k + 12, NovaCraftBlocks.carved_vanite_brick_stairs, 1, 2);
        world.setBlock(i + 13, j + 12, k + 13, NovaCraftBlocks.carved_vanite_brick_stairs, 3, 2);

        world.setBlock(i + 13, j + 8, k + 12, Blocks.diamond_block, 0, 2);

        world.setBlock(i + 15, j + 7, k + 16, Blocks.chest, 2, 2);
        TileEntityChest chest = (TileEntityChest) world.getTileEntity(i + 15, j + 7, k + 16);
        for (int slot = 0; slot < 3 + random.nextInt(20); slot++) {
            chest.setInventorySlotContents(random.nextInt(chest.getSizeInventory()), this.getChestLoot(random));
        }

        world.setBlock(i + 10, j + 7, k + 8, Blocks.chest, 3, 2);
        TileEntityChest chest2 = (TileEntityChest) world.getTileEntity(i + 10, j + 7, k + 8);
        for (int slot = 0; slot < 3 + random.nextInt(20); slot++) {
            chest2.setInventorySlotContents(random.nextInt(chest2.getSizeInventory()), this.getChestLoot(random));
        }

        return true;
    }

    private ItemStack getChestLoot(Random random) {
        int item = random.nextInt(15);
        switch (item) {
            case 0:
                return new ItemStack(Items.iron_ingot, random.nextInt(4) + 3);
            case 1:
                return new ItemStack(NovaCraftBlocks.cobbled_etherstone, random.nextInt(8) + 3);
            case 2:
                return new ItemStack(NovaCraftItems.aether_shard);
            case 3:
                return new ItemStack(NovaCraftItems.vanite_ingot, random.nextInt(5) + 4);
            case 4:
                return new ItemStack(NovaCraftItems.iridium_nugget, random.nextInt(4) + 3, 0);
            case 5:
                return new ItemStack(NovaCraftItems.copartz_shard, random.nextInt(3) + 1);
            case 6:
                return new ItemStack(NovaCraftItems.tsavorokite_shard, random.nextInt(2) + 1);
            case 7:
                return new ItemStack(NovaCraftItems.larimar_shard, random.nextInt(2) + 1);
            default: {
                return new ItemStack(Items.gold_ingot, random.nextInt(9) + 3);
            }
        }
    }

    private Block placeEtherstoneBricks(Random random) {
        if (random.nextDouble() <= 0.02) {
            return Blocks.air;
        } else if (random.nextDouble() > 0.02 && random.nextDouble() < 0.06) {
            return NovaCraftBlocks.cracked_etherstone_bricks;
        } else {
            return NovaCraftBlocks.etherstone_bricks;
        }
    }

    private Block placeEtherstoneBrickStairs(Random random) {
        if (random.nextDouble() <= 0.05) {
            return Blocks.air;
        } else {
            return NovaCraftBlocks.etherstone_brick_stairs;
        }
    }

    private Block placeCarvedVaniteBricks(Random random) {
        if (random.nextDouble() <= 0.05) {
            return Blocks.air;
        } else {
            return NovaCraftBlocks.carved_vanite_bricks;
        }
    }
}
