package com.NovaCraft.world.floating_island;

import com.NovaCraft.Items.NovaCraftItems;
import com.NovaCraftBlocks.NovaCraftBlocks;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityMobSpawner;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenAbstractTree;

import java.util.Random;

public class FloatingIslandRuins extends WorldGenAbstractTree
{

    public FloatingIslandRuins(final Block block, final int height, final boolean branch) {
        super(true);
    }

    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {


        world.setBlock(i + 2, j, k, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 1, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 2, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 3, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 4, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 5, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 6, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 7, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 8, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 9, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 10, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 11, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 12, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 13, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 14, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 15, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 16, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 17, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 18, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 19, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 20, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 21, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 7, j, k + 22, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 1, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 6, j, k + 23, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 3, j, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 4, j, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 5, j, k + 24, NovaCraftBlocks.rich_etherstone, 0, 2);
        world.setBlock(i + 2, j + 1, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 1, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 1, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 1, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 1, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 1, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 2, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 2, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 2, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 2, NovaCraftBlocks.welkin_log, 0, 2);
        world.setBlock(i + 5, j + 2, k + 2, placeEtherStoneTileStairs(random), 0, 2);
        world.setBlock(i + 6, j + 2, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 2, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 6, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 6, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 7, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 7, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 8, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 8, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 9, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 9, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 10, placeEtherStoneTileStairs(random), 3, 2);
        world.setBlock(i + 3, j + 2, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 10, placeLadder(random), 4, 2);
        world.setBlock(i + 6, j + 2, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 11, NovaCraftBlocks.welkin_log, 0, 2);
        world.setBlock(i + 3, j + 2, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 1, j + 2, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 2, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 1, j + 2, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 13, placeLadder(random), 5, 2);
        world.setBlock(i + 3, j + 2, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 13, placeEtherStoneTileStairs(random), 2, 2);
        world.setBlock(i + 6, j + 2, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 14, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 14, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 15, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 15, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 16, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 16, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 17, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 17, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 18, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 18, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 19, Blocks.carpet, 8, 2);
        world.setBlock(i + 3, j + 2, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 19, Blocks.carpet, 8, 2);
        world.setBlock(i + 6, j + 2, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 20, Blocks.carpet, 8, 2);
        world.setBlock(i + 3, j + 2, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 20, Blocks.carpet, 8, 2);
        world.setBlock(i + 6, j + 2, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 2, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 2, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 2, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 2, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 2, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 22, placeEtherStoneTileStairs(random), 1, 2);
        world.setBlock(i + 3, j + 2, k + 22, NovaCraftBlocks.welkin_log, 0, 2);
        world.setBlock(i + 4, j + 2, k + 22, NovaCraftBlocks.welkin_log, 0, 2);
        world.setBlock(i + 5, j + 2, k + 22, placeEtherStoneTileStairs(random), 0, 2);
        world.setBlock(i + 6, j + 2, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 2, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 2, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 2, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 2, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 3, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 3, k + 1, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 2, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 3, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 4, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 5, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 6, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 6, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 7, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 7, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 8, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 8, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 9, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 9, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 10, placeLadder(random), 4, 2);
        world.setBlock(i + 6, j + 3, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 1, j + 3, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 1, j + 3, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 13, placeLadder(random), 5, 2);
        world.setBlock(i + 3, j + 3, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 14, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 14, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 15, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 15, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 16, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 16, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 17, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 17, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 18, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 18, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 19, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 20, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 21, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 3, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 22, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 3, k + 22, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 3, k + 22, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 3, k + 22, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 3, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 3, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 3, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 3, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 3, k + 23, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 2, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 3, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 4, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 5, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 6, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 7, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 8, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 4, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 10, Blocks.trapdoor, 10, 2);
        world.setBlock(i + 6, j + 4, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 4, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 11, Blocks.glass, 0, 2);
        world.setBlock(i + 4, j + 4, k + 11, Blocks.glass, 0, 2);
        world.setBlock(i + 5, j + 4, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 4, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 12, Blocks.glass, 0, 2);
        world.setBlock(i + 4, j + 4, k + 12, Blocks.glass, 0, 2);
        world.setBlock(i + 5, j + 4, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 4, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 13, Blocks.trapdoor, 11, 2);
        world.setBlock(i + 3, j + 4, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 4, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 15, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 16, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 17, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 18, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 19, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 20, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 21, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 4, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 4, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 4, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 4, k + 22, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 5, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 5, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 5, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 5, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 5, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 5, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 5, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 5, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 5, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 5, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 5, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 5, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 5, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 5, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 5, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 5, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 5, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 5, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 5, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 5, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 5, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 5, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 5, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 5, k + 13, Blocks.carpet, 8, 2);
        world.setBlock(i + 5, j + 5, k + 13, Blocks.carpet, 8, 2);
        world.setBlock(i + 6, j + 5, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 5, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 5, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 5, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 5, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 6, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 6, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 6, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 6, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 6, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 6, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 6, k + 10, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 6, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 6, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 6, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 6, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 6, k + 11, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 6, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 6, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 6, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 6, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 6, k + 12, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 6, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 6, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 3, j + 6, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 4, j + 6, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 5, j + 6, k + 13, Blocks.air, 0, 2);
        world.setBlock(i + 6, j + 6, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 6, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 6, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 6, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 6, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 9, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 7, k + 10, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 7, k + 11, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 7, k + 12, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 1, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 6, j + 7, k + 13, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 2, j + 7, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 3, j + 7, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 4, j + 7, k + 14, placeEtherStoneBricks(random), 0, 2);
        world.setBlock(i + 5, j + 7, k + 14, placeEtherStoneBricks(random), 0, 2);

        world.setBlock(i + 3, j + 2, k + 3, Blocks.mob_spawner, 0, 2);
        TileEntityMobSpawner tileentitymobspawner = (TileEntityMobSpawner)world.getTileEntity(i + 3, j + 2, k + 3);

        if (tileentitymobspawner != null)
        {
            tileentitymobspawner.func_145881_a().setEntityName("nova_craft.soloid");
        }

        world.setBlock(i + 2, j + 5, k + 10, Blocks.mob_spawner, 0, 2);
        TileEntityMobSpawner tileentitymobspawner2 = (TileEntityMobSpawner)world.getTileEntity(i + 2, j + 5, k + 10);

        if (tileentitymobspawner2 != null)
        {
            tileentitymobspawner2.func_145881_a().setEntityName("nova_craft.soloid");
        }

        world.setBlock(i + 2, j + 2, k + 5, Blocks.chest, 5, 2);
        TileEntityChest chest = (TileEntityChest) world.getTileEntity(i + 2, j + 2, k + 5);

        for (int slot = 0; slot < 3 + random.nextInt(20); slot++) {
            chest.setInventorySlotContents(random.nextInt(chest.getSizeInventory()), this.getChestLoot(random));
        }

        world.setBlock(i + 5, j + 5, k + 12, Blocks.chest, 4, 2);
        TileEntityChest chest2 = (TileEntityChest) world.getTileEntity(i + 5, j + 5, k + 12);

        for (int slot = 0; slot < 3 + random.nextInt(20); slot++) {
            chest2.setInventorySlotContents(random.nextInt(chest2.getSizeInventory()), this.getChestLoot(random));
        }

        return true;
    }

    private Block placeEtherStoneBricks(Random random) {
        if (random.nextDouble() < 0.65) {
            return NovaCraftBlocks.etherstone_bricks;
        } else if (random.nextDouble() < 0.85) {
            return NovaCraftBlocks.cracked_etherstone_bricks;
        } else {
            return Blocks.air;
        }
    }

    private Block placeEtherStoneTileStairs(Random random) {
        if (random.nextDouble() < 0.65) {
            return NovaCraftBlocks.etherstone_tiled_stairs;
        } else {
            return Blocks.air;
        }
    }

    private Block placeLadder(Random random) {
        if (random.nextDouble() < 0.75) {
            return Blocks.ladder;
        } else {
            return Blocks.air;
        }
    }

    private ItemStack getChestLoot(Random random) {
        int item = random.nextInt(15);
        switch (item) {
            case 0:
                return new ItemStack(Items.iron_ingot, random.nextInt(4) + 3);
            case 1:
                return new ItemStack(NovaCraftBlocks.cobbled_etherstone, random.nextInt(8) + 3);
            case 2:
                return new ItemStack(NovaCraftItems.aether_shard);
            case 3:
                return new ItemStack(NovaCraftItems.vanite_ingot, random.nextInt(5) + 4);
            case 4:
                return new ItemStack(NovaCraftItems.iridium_nugget, random.nextInt(4) + 3, 0);
            case 5:
                return new ItemStack(NovaCraftItems.copartz_shard, random.nextInt(3) + 1);
            case 6:
                return new ItemStack(NovaCraftItems.tsavorokite_shard, random.nextInt(2) + 1);
            case 7:
                return new ItemStack(NovaCraftItems.larimar_shard, random.nextInt(2) + 1);
            case 8:
                return new ItemStack(Items.gold_ingot, random.nextInt(9) + 3);
            case 9:
                return new ItemStack(NovaCraftBlocks.welkin_log, random.nextInt(8) + 3);
            default: {
                return new ItemStack(NovaCraftItems.diamond_nugget, random.nextInt(7) + 5, 2);
            }
        }
    }
}
